content/docs/installation/helm/isilon.md

Release updates

---

content/docs/deployment/csmapi.md
content/docs/deployment/swagger.yaml

Release updates 

---

content/docs/authorization/troubleshooting.md

Add info how to retrieve CSM Authorization proxy-server logs for proxy server and OPA

Add info how to retrieve CMS auth server logs

---

content/docs/observability/troubleshooting/_index.md

This PR adds a section to the troubleshooting guide for CSM Observability to upgrade cert-manager to the latest version

Add instructions to upgrade cert-manager for CSM observability

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/replication/_index.md

This PR updates the Hickory SR version supported by PowerMax.

Update Hickory SR version

---

content/docs/observability/deployment/helm.md
content/docs/observability/upgrade/_index.md

Updated upgrade documentation for observability

Update observability upgrade

---

content/docs/contributionguidelines/_index.md

Small update to the contributing documentation around proper branching strategy.
| N/A |

Small update to the contributing doc

---

content/v1/features/powerflex.md

This PR adds documentation for the new volume health monitor feature in CSI-PowerFlex
| https://github.com/dell/csm/issues/84|

add Volume Health Monitor section

---

content/docs/csidriver/features/powerflex.md

Powerflex readwriteoncepod Feature

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md

| https://github.com/dell/csm/issues/73 |

pv/pvc metrics csi-powerstore changes

---

content/docs/authorization/troubleshooting.md

Added troubleshooting documentation about gateway timeout for authorization.
| |

Added troubleshooting documentation about gateway timeout for authorization

---

content/docs/replication/tools.md
content/docs/replication/uninstall.md

| https://github.com/dell/csm/issues/70 |
| https://github.com/dell/csm/issues/66 |
Related PRs: 
| GitHub Pull Request# |
| https://github.com/dell/csm-replication/pull/15 |

[replication] Added uninstall page, updated repctl readme

---

content/docs/csidriver/features/powerstore.md
content/v1/features/powerstore.md
content/v2/features/powerstore.md
content/v3/features/powerstore.md

static provisioning and ephemeral changes

---

content/docs/authorization/deployment/_index.md

Updated Authorization deployment steps
|https://github.com/dell/csm/issues/78 |

Updated Authorization deployment steps

---

content/docs/csidriver/installation/helm/powerflex.md

This PR should be merged after https://github.com/dell/csi-powerflex/pull/44 gets merged
Adds healthMonitorInterval  documentation to values table
| https://github.com/dell/csm/issues/84 |

add  healthMonitorInterval to values table

---

.github/CODEOWNERS

Updating code owners and fixed typo in filename
| |

update code owners - release 1.1

---

content/docs/csidriver/features/powerflex.md
content/v1/features/powerflex.md

This PR moves the health monitor section to the correct file
| |

Move health monitor section to correct file 

---

content/docs/csidriver/troubleshooting/powerflex.md

adding troubleshooting scenario

---

content/docs/replication/_index.md

Removed older OpenShift and added new driver versions
| |

[replication] Removed older OpenShift and added new driver versions

---

content/docs/csidriver/features/powerstore.md

Added documentation on the new alpha feature RWOP for CSI Powerstore
| dell/csm#76 |

Feature rwop csi powerstore

---

content/docs/csidriver/features/powerscale.md

Documentation update about new feature support in csi-powerscale - RWOP access mode
| dell/csm#80|

Feature rwop accessmode support for csi-powerscale

---

content/docs/csidriver/features/unity.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/unity.md

Tenant documentation for both csi-unity and operator
KRV-674
Also addressed comments from previous pr : https://github.com/dell/csm-docs/pull/82 and created from release-1.1 branch
- [x ] Have you run a grammar and spell checks against your submission?
- [ x] Have you tested whether the hyperlinks are working properly?
- [x ] Did you add the examples wherever applicable?

Tenant documentation for both csi-unity and operator

---

content/docs/replication/_index.md

Changed replication support matrix because right now the team isn't comfortable claiming support for OpenShift with PowerMax

Changed replication support matrix

---

content/docs/csidriver/features/unity.md
content/docs/csidriver/installation/helm/unity.md

Add the below features in Unity
ReadWriteOncePod accessmode 
Volume Health Monitoring 
|dell/csm#94|
|dell/csm#76|

Rwop volumehealth

---

content/docs/csidriver/installation/operator/_index.md

Operator upgrade documentation for volume health monitor changes
- [x ] Have you run a grammar and spell checks against your submission?
- [ x] Have you tested whether the hyperlinks are working properly?
- [ x] Did you add the examples wherever applicable?

Operator upgrade documentation for volume health monitor changes

---

content/docs/snapshots/_index.md

Based on feedback, adding a note with kubectl command for listing VolumeSnapshots.
| |

Added note about how to list volume snapshots

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/isilon.md

Improve documentation on operator installation and upgrade.
1. Updated content/docs/csidriver/installation/helm/isilon.md to reflect the right filename of the empty secret file.
2. Updated content/docs/csidriver/installation/operator/_index.md to add step to install snapshot-controller, which is checked during installation of operator. 
Added step to checkout the branch so customer is aware which version is chosen for installation.
Added option to upgrade using kubectl apply which seemed easier than others.
3. Updated content/docs/csidriver/installation/operator/isilon.md to reflect the namespace that is present in the sample files which the customer will refer.
| https://github.com/dell/csm/issues/110 |

Improve operator install steps

---

content/docs/csidriver/features/powerscale.md

https://github.com/dell/csm/issues/82
topology usage is updated 
| https://github.com/dell/csm/issues/82|

updated sample update for topology usage

---

content/docs/replication/_index.md

Updated the document for Metro mode . For creating volume with Metro mode we do not need replicator sidecar and common controller . We are supporting this mode at driver level only. 
|  #[135](https://github.com/dell/csm/issues/135)          |

Updating Replication doc for metro mode 

---

content/docs/observability/_index.md

Updated supported versions for Observability.
|  https://github.com/dell/csm/issues/136 |

Updated supported versions of k8s for observability

---

content/docs/FAQ/_index.md
content/docs/deployment/csminstaller/_index.md
content/docs/observability/deployment/_index.md

Removes reference of the CSM Installer as the recommended installation method for Observability.
Removes references of the CSM Installer from the FAQ for recommended installation.
Moved and bolded the note detailing 1.0 and non-upgrade support for the CSM Installer to be more visible.
| https://github.com/dell/csm/issues/154 |

Updated references about the CSM Installer

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/upgradation/drivers/isilon.md
content/docs/csidriver/upgradation/drivers/operator.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/csidriver/upgradation/drivers/unity.md

Improve documentation for operator upgrade and driver upgrade via operator
https://github.com/dell/csm/issues/127
https://github.com/dell/csm/issues/127
| |

Operator upgrade steps improvement

---

content/docs/csidriver/features/powerscale.md

documentation for driver enhancement- allow volume creation from snapshot with different isi path

documentation for driver enhancement- allow volume creation from snapshot with different isi path

---

content/docs/observability/deployment/online.md
content/docs/observability/troubleshooting/_index.md

This PR updates Observability installer usage details and adds to Observability troubleshooting.
|https://github.com/dell/csm/issues/112 |

Update Observability installer with Authorization and troubleshooting

---

content/docs/observability/_index.md

This PR adds Powerstore 2.1 (Malka) as a supported storage platform for Observability.
| |

Add observability support for PowerStore Malka release

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md

PV/PVC metrics feature for PowerMax
|https://github.com/dell/csm/issues/174 |

PV/PVC metrics feature for PowerMax

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powermax.md

RWOP support for PowerMax documentation
|https://github.com/dell/csm/issues/175|

RWOP powermax

---

content/docs/csidriver/features/powerflex.md

Update powerflex.md feature vg snapshot to 1.0

---

config.toml
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Updates for Operator changes for PowerMax
| https://github.com/dell/csm/issues/195 |

Updates for operator changes for powermax

---

content/docs/csidriver/installation/test/powermax.md

Added details for editing application prefix for PowerMax 
| https://github.com/dell/csm/issues/201 |

Application prefix for PowerMax documentation

---

content/docs/csidriver/installation/test/powermax.md

Adding application prefix information for PowerMax
| https://github.com/dell/csm/issues/201 |

Adding application prefix information for PowerMax

---

content/docs/csidriver/installation/helm/unity.md

Docs was pointing to the wrong directory.
Remove note on external-snapshotter referring to a non-updated repository

Fix path to csi-unity/samples & align table

---

content/docs/authorization/deployment/_index.md

This PR attempts to clarify the certificate configuration steps for CSM Authorization deployment.
| https://github.com/dell/csm/issues/197|

Update Authorization Proxy Server Deployment Steps

---

content/docs/_index.md

Quick fix to update the correct supported version of podmon for CSM 1.1
| NA|

Fix csm resiliency version

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

Added documentation for NVMeTCP for Powerstore

---

content/docs/csidriver/installation/helm/powerstore.md

Updated documentation for FSGroup policy
| https://github.com/dell/csm/issues/167 |

updated document for fsgroup

---

content/docs/replication/deployment/installation.md
content/docs/replication/deployment/powermax.md
content/docs/replication/deployment/powerscale.md
content/docs/replication/deployment/powerstore.md
content/docs/replication/deployment/storageclasses.md
content/docs/replication/disaster-recovery.md
content/docs/replication/replication-actions.md

- Added PowerScale replication section
- Fixed a couple of formatting issues
- Added PowerScale actions descriptions
| https://github.com/dell/csm/issues/116 |

[replication] Added PowerScale replication section

---

content/docs/csidriver/installation/test/powermax.md

Added example for static provisioning of PowerMax volumes
| https://github.com/dell/csm/issues/169 |

Static provisioning for powermax

---

content/docs/csidriver/features/unity.md

Related to https://github.com/dell/csi-unity/pull/67  ; I did not change the ephemeral volume example since I did not test it myself
|https://github.com/dell/csm/issues/188 |

Unity change `fsType` to `csi.storage.k8s.io/fstype` 

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

NVMe TCP Support for Powerstore Documentation Update
|https://github.com/dell/csm/issues/158|

NVMe/TCP Documentation

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

Reverted NVMe docs from `main`
| https://github.com/dell/csm/issues/158 |

Reverted NVMe docs

---

content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/unity.md

Standalone helm installer changes for complex K8s version
| https://github.com/dell/csm/issues/195 |

Standalone helm installer changes for complex K8s version

---

content/docs/csidriver/installation/operator/powerflex.md

- Made changes to operator docs for powerflex-v2.2.0
- Added external health-monitor support
| |

operator changes for powerflex-v2.2.0

---

content/docs/FAQ/_index.md
content/docs/csidriver/features/powerstore.md

PR for adding the Powerstore OE support for NVMe TCP
|https://github.com/dell/csm/issues/158|

NVMe/TCP OE Support

---

content/docs/csidriver/features/powerstore.md

PR for updating the NVMe/TCP support Matrix for Powerstore
|https://github.com/dell/csm/issues/158|

Nv me support matrix change

---

content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/powerscale.md
content/docs/deployment/csmoperator/modules/_index.md
content/docs/deployment/csmoperator/modules/authorization.md
content/docs/deployment/csmoperator/troubleshooting/_index.md

Fix broken links in CSM Operator
| https://github.com/dell/csm/issues/159 |

Fix broken links in CSM Operator

---

content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/powerscale.md
content/docs/deployment/csmoperator/troubleshooting/_index.md

Updated docs for csm operator

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powerflex.md

Added amazon EKS support for PowerFlex 
| https://github.com/dell/csm/issues/223 |

Added amazon EKS support for PowerFlex 

---

config.toml
content/docs/FAQ/_index.md
content/docs/_index.md
content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/csidriver/upgradation/drivers/isilon.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/csidriver/upgradation/drivers/unity.md
content/docs/deployment/csmoperator/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Updated the version changes for all drivers and modules
| https://github.com/dell/csm/issues/188 |

v2.3.0 changes for all drivers and modules 

---

config.toml
content/docs/FAQ/_index.md
content/docs/_index.md
content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/csidriver/troubleshooting/powerflex.md
content/docs/csidriver/upgradation/drivers/isilon.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/csidriver/upgradation/drivers/unity.md
content/docs/deployment/csmoperator/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Adds an entry to the troubleshooting section. 
| https://github.com/dell/csm/issues/236 |

Add troubleshooting entry

---

config.toml
content/docs/FAQ/_index.md
content/docs/_index.md
content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/csidriver/troubleshooting/powerflex.md
content/docs/csidriver/upgradation/drivers/isilon.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/csidriver/upgradation/drivers/unity.md
content/docs/deployment/csmoperator/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Revert "Add troubleshooting entry"

---

content/docs/csidriver/troubleshooting/powerflex.md

This PR adds a trouble shooting entry
|  https://github.com/dell/csm/issues/236 |

Add trouble-shooting entry

---

content/docs/csidriver/release/powerscale.md

Release note updated for beta sample removed in CSI-PowerScale
| https://github.com/dell/csm/issues/239 |

Release note updated for beta sample removed in CSI-PowerScale

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md

Updated correct deployment method for CRDs and the default snapshot controller
| https://github.com/dell/csm/issues/250 |

Deployment method for CRDs and the default snapshot controller - updates

---

.github/CODEOWNERS

Fix code owner file - Invalid file format bug fixing 
| https://github.com/dell/csm/issues/274 |

Bug - Fix code owner file

---

content/docs/csidriver/_index.md

Added support for amazon EKS for Powerstore
|https://github.com/dell/csm/issues/283 |

Added support for amazon EKS for Powerstore

---

content/docs/csidriver/release/powermax.md

Updated release notes for PMAX- PVC/PV mapping to namespace
| https://github.com/dell/csm/issues/272 |

Updated release notes for PMAX- PVC/PV mapping to namespace

---

content/docs/csidriver/installation/helm/unity.md

Documentation on standalone installer and vtag for csi unity driver
- [] Have you run a grammar and spell checks against your submission?

Documentation on standalone installer and version tag for csi unity driver

---

content/docs/csidriver/installation/helm/unity.md

Documentation on standalone installer and vtag for csi unity driver
- [] Have you run a grammar and spell checks against your submission?

Documentation on standalone installer and vtag for csi unity driver

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/operator.md

Operator docs changes to update versions reference.
|https://github.com/dell/csm/issues/243|

Update supported version references in CSI operator docs

---

content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/release/unity.md

1. CSI Driver for Unity documentation for FC and multipath prerequisites
2. Resiliency: Occasional failure unmounting Unity volume for raw block devices via iSCSI
| https://github.com/dell/csm/issues/284  https://github.com/dell/csm/issues/237 |

CSI Driver for Unity documentation for FC and multipath prerequisites

---

content/docs/FAQ/_index.md
content/docs/_index.md

Update CSM support matrix to home page 
| https://github.com/dell/csm/issues/287 |

Update CSM support matrix to home page 

---

content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Added  fsgroup policy support for PowerMax 
| https://github.com/dell/csm/issues/285 |

Added fsgroup policy

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Documentation of feature "Enhanced topology control for PowerMax"
| https://github.com/dell/csm/issues/293 |

Enhanced topology control for PowerMax

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

Documentation Update for NVMeFC Support for Powerstore.
|https://github.com/dell/csm/issues/260|

Powerstore NVMeFC support

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/release/powerstore.md

Documentation updates for Configurable volume attributes feature
| dell/csm#291 |

Configurable volume attributes

---

content/docs/authorization/release/_index.md
content/docs/observability/release/_index.md
content/docs/release/_index.md
content/docs/replication/release/_index.md
content/docs/resiliency/release/_index.md

Release notes pages for modules

Release notes pages for modules

---

content/docs/csidriver/release/powerflex.md

Updates documentation 
|  https://github.com/dell/csm/issues/243   |

pflex-updates

---

content/docs/deployment/csmoperator/_index.md

Add note to documentation that we now support upgrading drivers in csm-operator.
| https://github.com/dell/csm/issues/255 |

add support for upgrade

---

content/docs/csidriver/release/powerstore.md

PR for adding NVMeFC in the release notes.
|https://github.com/dell/csm/issues/260|

Updating Release Notes

---

content/docs/csidriver/installation/helm/unity.md
content/docs/deployment/csmoperator/_index.md

Update the documentation for operator upgrade.
| https://github.com/dell/csm/issues/243|

Update the documentation for operator upgrade

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/operator/powermax.md

Release 1.3 changes for PowerMax -2 
| https://github.com/dell/csm/issues/244 |

Release 1.3 changes for PowerMax -2 

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/release/powerscale.md
content/docs/resiliency/upgrade.md

Add resiliency in release notes of powerscale driver.
Add powerscale in resiliency driver
https://github.com/dell/csm/issues/262
https://github.com/dell/csm/issues/262

Add powerscale upgrade to upgrade in resiliency section

---

content/docs/_index.md
content/docs/csidriver/_index.md

Module support matrix - moving to the home page 
| https://github.com/dell/csm/issues/243|

Module support matrix - moving to home page 

---

content/docs/csidriver/_index.md

Add support for PowerStore OE 3.0
| dell/csm#176 |

Adding support for OE 3.0

---

content/docs/_index.md
content/docs/authorization/_index.md
content/docs/authorization/cli.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/release/_index.md
content/docs/observability/_index.md
content/docs/observability/release/_index.md
content/docs/resiliency/release/_index.md

Fixing missing prerequisites for CSM Authorization, revoke tenant call, typos, and version updates
|https://github.com/dell/csm/issues/313 |

modules doc bug fixes

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/upgradation/drivers/powerflex.md

Making some minor version-related changes and moving a field in values into the correct place.
| https://github.com/dell/csm/issues/256 |

PowerFlex version and values updates

---

content/docs/csidriver/installation/helm/powerflex.md

fix indents

---

content/docs/csidriver/features/powerstore.md
content/docs/snapshots/volume-group-snapshots/_index.md

Added a note for helm supported features
| |

Feature support note

---

content/docs/deployment/csmoperator/drivers/powerscale.md
content/docs/deployment/csmoperator/modules/_index.md
content/docs/deployment/csmoperator/modules/authorization.md
content/docs/deployment/csmoperator/modules/replication.md

This PR contains Documentation for Replication support in Dell CSM Operator
| https://github.com/dell/csm/issues/270|

adds documentation for replication

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/test/powermax.md
content/docs/csidriver/release/powermax.md

Device expansion not supported for PowerMax replicated volumes
|https://github.com/dell/csm/issues/327 |

Device expansion not supported for PowerMax replicated volumes

---

content/docs/replication/_index.md

Realign & organize the tables. Add metro replication in support matrix.
| |

Reorganize support matrixes

---

content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/unity.md

Incorporating feedback got from team review on Unity XT docs.

Feature 243 Incorporate team docs review comments

---

content/docs/resiliency/_index.md
content/docs/resiliency/release/_index.md

Update CSM for Resiliency documentation update for
Release note
Multi-array support and connectivity state on multi-array setup
| #https://github.com/dell/csm/issues/333 |

Update CSM for Resiliency documentation update

---

content/docs/authorization/_index.md
content/docs/authorization/deployment/helm/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/troubleshooting.md

Updated Authorization Troubleshooting Guide
| https://github.com/dell/csm/issues/313 |

Updated Authorization Troubleshooting Guide

---

content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md

Adding missing parameters in powermax yaml files 

Doc changes powermax

---

content/docs/_index.md
content/docs/authorization/_index.md

PR to update the CSM Authorization release version for v1.3.0 release
|https://github.com/dell/csm/issues/243|

Update authorization sidecar v1.3.0 version

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/upgradation/drivers/operator.md
content/v1/csidriver/installation/operator/_index.md
content/v1/csidriver/upgradation/drivers/operator.md

Updated operator installation steps
| https://github.com/dell/csm/issues/345|

Bugfix 345 update operator clone steps

---

content/docs/authorization/deployment/helm/_index.md

PR to reference how to install karavictl for Authorization helm deployment.
|https://github.com/dell/csm/issues/346 |

Update CSM Authorization Helm Deployment

---

content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/upgradation/drivers/operator.md
content/v1/csidriver/installation/offline/_index.md
content/v1/csidriver/installation/operator/_index.md
content/v1/csidriver/upgradation/drivers/operator.md

Improvements to Operator installation docs
|https://github.com/dell/csm/issues/345 |

Minor improvements to Operator installation docs

---

content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/operator/powerflex.md

This PR adds a note about mpath and PowerFlex in the install section
|https://github.com/dell/csm/issues/350 |

Enhance pflex install

---

.github/CODEOWNERS

Updated code owners file
|https://github.com/dell/csm/issues/350 |

Updating code owners file

---

content/docs/csidriver/_index.md
content/docs/csidriver/partners/tanzu.md

Support iSCSI in CSI PowerStore on VMware Tanzu
| dell/csm#363 |

Support iSCSI in CSI PowerStore on VMware Tanzu

---

content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/release/unity.md

Documentation for fsgroupPolicy support in CSI Unity Driver
|https://github.com/dell/csm/issues/361 |

Docs updates for fsgrouppolicy support in CSI Unity driver

---

content/docs/authorization/deployment/helm/_index.md
content/docs/authorization/deployment/rpm/_index.md

Description
This PR will update the document to pick the latest changes in authorization.
](https://github.com/dell/csm/issues/368)
Checklist:

Document changes for authorization

---

.github/workflows/deploy.yml
.github/workflows/deploy1.yml

Upgrade the dependencies to latest docsy

Fix workflows

---

.github/workflows/deploy.yml
.github/workflows/deploy1.yml

Fix the known issue of docsy in the workflow 
https://github.com/google/docsy/issues/705

Fix known docsy issue in the workflow 

---

content/docs/csidriver/release/powermax.md

Updating known issues for PowerMax
| https://github.com/dell/csm/issues/386 |

updating known issues

---

assets/js/offline-search.js

Fixed search the webste 
|https://github.com/dell/csm/issues/387 |

Fixed offline search

---

go.mod
go.sum

Updated docsy to latest release 
|  https://github.com/dell/csm/issues/387 |

Updated docsy to latest release 

---

content/docs/_index.md

Updated the index page to include cards of modules, removed duplicate displays 
| https://github.com/dell/csm/issues/357 |

Update home page

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/release/powermax.md
content/docs/replication/_index.md
content/docs/replication/volume_expansion.md

Adding volume expansion support for replicated  for PowerMax
| https://github.com/dell/csm/issues/336 |

Adding volume expansion support for replicated 

---

content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

Reordering the subsection of Volume Snapshot feature & steps of installing driver
| dell/csm#350 |

Doc modification

---

content/docs/authorization/deployment/helm/_index.md

Updates instructions for downloading and installing karavictl.
|https://github.com/dell/csm/issues/360 |

Update instructions for installing karavictl

---

content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

- Update `Volume Snapshot Controller` section.
- Reorder 5  and 6 steps in `Install the Driver` section.
- Update Install Driver section in Operator installation.
| dell/csm#350 |

CSI-Powerstore: Update Installation doc

---

content/docs/replication/deployment/installation.md
content/docs/replication/deployment/storageclasses.md
content/docs/replication/deployment/unity.md
content/docs/replication/replication-actions.md

Added Unity replication section
| https://github.com/dell/csm/issues/381|

[replication] Added Unity replication section

---

content/docs/license/_index.md
content/docs/support/license.md

Add documentation about how to request a license for Application Mobility and Encryption

Added documentation about requesting a license

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/release/powermax.md
content/docs/replication/_index.md

Juniper Support for PowerMax
| https://github.com/dell/csm/issues/389 |

Juniper Support for PowerMax

---

content/docs/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/references/_index.md
content/docs/release/_index.md
content/docs/secure/_index.md
content/docs/secure/encryption/_index.md
content/docs/secure/encryption/deployment.md
content/docs/secure/encryption/troubleshooting.md
content/docs/secure/encryption/uninstallation.md
content/docs/secure/encryption/vault.md
content/docs/support/_index.md
content/docs/troubleshooting/_index.md

Add documentation about Encryption

Feature csm encryption

---

content/docs/csidriver/features/powerscale.md

Mentioned step to add quota ID for static provisioned volumes for which quota is enabled.
https://github.com/dell/csm/issues/433

CSI-Powerscale - add quota ID for static provisioning

---

content/docs/csidriver/features/powerscale.md
content/docs/csidriver/upgradation/drivers/offline.md

Add steps to upgrade driver using using offline bundle
https://github.com/dell/csm/issues/421

Steps to upgrade driver using offline bundle

---

content/docs/csidriver/release/powerflex.md

Updated CSI-PowerFlex release notes for v2.4.0

csi-powerflex 2.4 release notes

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/release/operator.md
content/docs/csidriver/release/unity.md
content/docs/csidriver/upgradation/drivers/operator.md
content/docs/csidriver/upgradation/drivers/unity.md

Updated the operator version from 1.8 to 1.9
|https://github.com/dell/csm/issues/350 |

Version update for Dell CSI Operator 

---

content/docs/secure/encryption/_index.md
content/docs/secure/encryption/deployment.md
content/docs/secure/encryption/troubleshooting.md
content/docs/secure/encryption/uninstallation.md
content/docs/secure/encryption/vault.md

Amended and addressed feedback for the Encryption feature documentation.
| |

Amended and addressed feedback for the Encryption feature documentation.

---

content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md

Updated CSI-Powerstore docs for v2.4.0
| dell/csm#350|
| |

powerstore-2.4-changes

---

content/docs/csidriver/release/powerflex.md

Reverts https://github.com/dell/csm-docs/pull/327
Should not have merged this in main yet, reverting change

revert R.N. back to 1.3 version

---

content/docs/secure/encryption/release.md

Added a reference to a github issue to the release notes.
| |

Reference to github issue in release notes.

---

content/docs/_index.md
content/docs/applicationmobility/release.md

Updated documentation for Application Mobility

---

content/docs/release/_index.md

Added link to Application Mobility Release Notes

Added link to Application Mobility Release Notes

---

content/docs/csidriver/release/powerstore.md

PR for updating the new features in the release notes with a link to corresponding github issue
| |

CSI Powerstore Updated Release Notes

---

content/docs/observability/_index.md
content/docs/observability/release/_index.md

update observability release node with github issue links and support matrix.
| https://github.com/dell/csm/issues/455 |

update observability release node with github issue links and support matrix

---

content/docs/authorization/_index.md
content/docs/authorization/release/_index.md
content/docs/resiliency/release/_index.md

This PR will update the document for 1.4 release.
https://github.com/dell/csm/issues/350

Update document for latest release

---

content/docs/authorization/release/_index.md

This PR will remove the PR's from release notes.
https://github.com/dell/csm/issues/350

Remove PR from release notes for authorization

---

content/docs/resiliency/deployment.md

Update Resiliency deployment documentation to use v1.3.0 for the upcoming release.
|https://github.com/dell/csm/issues/442 |

Change Resiliency example image to v1.3.0

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md

PR for all the remaining documentation changes required for Powerstore
| |

Powerstore latest changes

---

content/docs/csidriver/_index.md

PR for PowerScale Anthos supported version update.
| |

powerscale anthos version update

---

content/docs/observability/deployment/offline.md

csm-metrics-powerscale should be 1.0.0 rather than 1.3.0
| https://github.com/dell/csm/issues/357 |

Fix csm-metrics-powerscale version

---

content/docs/csidriver/installation/helm/powerflex.md

Change volumeHealthMonitorInterval variable name to interval for PowerFlex.
| https://github.com/dell/csm/issues/203 |

Update values table with interval parameter in PowerFLex docs

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md

Modification in Volume health monitor config parameter 
|https://github.com/dell/csm/issues/203|

Doc update for healthMonitor parameter

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md

Reverting last commit for healthMonitor Parameter
| |

Reverting last commit

---

content/docs/secure/encryption/deployment.md

Update Encryption home page
| https://github.com/dell/csm/issues/357 |

Update Encryption home page

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/replication/_index.md
content/v1/authorization/_index.md
content/v1/csidriver/_index.md
content/v1/replication/_index.md
content/v2/authorization/_index.md
content/v2/csidriver/_index.md
content/v2/replication/_index.md
content/v3/authorization/_index.md
content/v3/csidriver/_index.md
content/v3/replication/_index.md

Update supported Powermax Matrix
| https://github.com/dell/csm/issues/489 |

Update supported Powermax Matrix

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/powermax.md
content/docs/replication/_index.md
content/docs/replication/release/_index.md

Updating K8 1.25 support for PowerMax driver 
| https://github.com/dell/csm/issues/478 |

Updating k8 1.25 support in PowerMax

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/replication/_index.md

Update PowerMax support matrix
| https://github.com/dell/csm/issues/489 |

Update PowerMax support matrix

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/operator/powerflex.md

Add a short clarifier for Pflex 4.0 systems 
|  https://github.com/dell/csm/issues/491 |

Pflex 4.0 docs

---

content/docs/csidriver/features/powermax.md
content/docs/replication/high-availability.md
content/v1/csidriver/features/powermax.md
content/v1/replication/high-availability.md
content/v2/csidriver/features/powermax.md
content/v2/replication/high-availability.md
content/v3/csidriver/features/powermax.md
content/v3/replication/high-availability.md

Update Replication release notes

---

content/docs/replication/deployment/powerscale.md

Updated repctl tool usage for [PowerScale replication fix](https://github.com/dell/csm-replication/pull/59)
| https://github.com/dell/csm/issues/514 |

Updated repctl tool usage for PowerScale replication

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md

Added Storage Capacity Tracking feature to PowerStore docs
| https://github.com/dell/csm/issues/483 |

Updated PowerStore docs for Storage Capacity Tracking feature

---

content/docs/csidriver/features/powerflex.md

Documentation update for adding support for setting of QoS limits by CSI-PowerFlex driver.
| https://github.com/dell/csm/issues/533 |

Powerflex docs: added support for setting QoS limits

---

content/docs/authorization/cli.md

Update the `role update` documentation to clarify that only quota can be updated.
| https://github.com/dell/csm/issues/530 |

[bug-350]: Update role update documentation

---

content/docs/deployment/csmoperator/modules/observability.md

add Observability in CSM Operator Deployment
| https://github.com/dell/csm/issues/488 |

add Observability in CSM Operator

---

content/docs/csidriver/_index.md
content/docs/replication/_index.md

Updating SLES SP4 support for PowerMax
| https://github.com/dell/csm/issues/539 |

Updating SLES SP4 support for PowerMax

---

content/docs/csidriver/features/powerflex.md

Documentation update for adding support for setting of QoS limits by CSI-PowerFlex driver.
| https://github.com/dell/csm/issues/533 |

csi-powerflex doc updated

---

content/docs/csidriver/_index.md

Updated supported Openshift version to 4.10, 4.11 for CSI-Powerflex

Update docs to OCP 4.10,4.11 for powerflex

---

content/docs/csidriver/_index.md

- Added 1.25 Kubernetes version
- Removed 1.22 Kubernetes version
- Updated SLES version to 15SP4
| dell/csm#478
| dell/csm#539

Powerflex documentation update: Added support for Kubernetes 1.25 and SLES 15SP4

---

content/docs/_index.md
content/docs/replication/_index.md

Consolidate duplicate table data, add details on file/block sync/async for replication module. Make landing page tables linkable to module specific docs. 
None
- [N/A] Did you add the examples wherever applicable?
- [N/A] Have you added high-resolution images?

Rework replication module docs

---

content/docs/csidriver/installation/helm/isilon.md

Reorganize the pre-req menu on the right, regroup all snapshot chapter together, add direct link to permission, add SyncIQ permission.
| |

Chapter csi powerscale

---

content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Reverse proxy mandate feature for CSI PowerMax
| https://github.com/dell/csm/issues/495 |

Reverse proxy mandate feature for CSI PowerMax

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/release/powermax.md

VMware/vSphere virtualization support via RDM
|https://github.com/dell/csm/issues/528 |

Feature : VMware/vSphere virtualization support via RDM for PowerMax

---

content/docs/references/cli/_index.md
content/docs/secure/encryption/_index.md
content/docs/secure/encryption/deployment.md
content/docs/secure/encryption/rekey.md
content/docs/secure/encryption/release.md
content/docs/secure/encryption/troubleshooting.md
content/docs/secure/encryption/uninstallation.md

Adding Encryption Rekey Feature.

---

content/docs/observability/deployment/offline.md
content/docs/observability/release/_index.md
content/docs/observability/upgrade/_index.md

Doc update for Observability 1.4
|https://github.com/dell/csm/issues/491|

Doc update for observability 1.4

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md

CSI-Powerstore: Updated driver version

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/installation/helm/powerflex.md

Documentation changes for the new Automated RHEL Sdc Deployment
| https://github.com/dell/csm/issues/554 |

CSI-Powerflex doc updates  for the 3.6.0.6  rhel sdc.

---

content/docs/references/cli/_index.md
content/docs/secure/encryption/_index.md
content/docs/secure/encryption/deployment.md
content/docs/secure/encryption/rekey.md
content/docs/secure/encryption/release.md
content/docs/secure/encryption/uninstallation.md

Overall pre-release updates related to the Encryption module.
| dell/csm#478 |
| dell/csm#480 |

csm-encryption pre-release updates.

---

content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/troubleshooting.md
content/docs/authorization/uninstallation.md
content/docs/authorization/upgrade.md

Updating the documentation for changes to deployment process for selinux installation.
|dell/csm#409 |

Updating documentation for selinux changes

---

content/docs/applicationmobility/deployment.md
content/docs/applicationmobility/release.md

Update versions of images for Application Mobility for CSM 1.5.
| https://github.com/dell/csm/issues/491|

Update versions of images and release notes for Application Mobility

---

content/docs/deployment/csmoperator/modules/observability.md

updated multiple drivers scenario for Observability in CSM Operator

updated multiple drivers scenario for Observability

---

content/docs/csidriver/_index.md

Updated Unity version format in storage support matrix
| https://github.com/dell/csm/issues/491|

Updated unity version format in support matrix

---

config.toml
content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/unity.md
content/docs/csidriver/upgradation/drivers/powermax.md

Common changes of CSM versions
|https://github.com/dell/csm/issues/491 |

Common changes for all drivers

---

content/docs/authorization/deployment/helm/_index.md
content/v1/authorization/deployment/helm/_index.md

Updated the security fix
|https://github.com/dell/csm/issues/491 |

Updated the security fix

---

content/docs/csidriver/installation/helm/isilon.md

Add the mandatory dependency
| |

Add nfs-utils dependency

---

content/docs/replication/deployment/powerscale.md
content/docs/replication/deployment/powerstore.md
content/docs/replication/deployment/unity.md

Updated the drivers readme for Powerstore, Powerscale and Unity about the limitation of volumeGroupPrefix
| [451](https://github.com/dell/csm/issues/451) |

Bug 451 - Replication documentation update for character count limits of 64

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md

Updated external snapshotter version to v6.1.0 to all drivers.
Updated operator docs for PowerStore with storage capacity tracking feature.
| https://github.com/dell/csm/issues/483 |

Updated external snapshotter version for all drivers & PowerStore related changes

---

content/docs/observability/_index.md

add PowerStore 3.2 in Observability support matrix

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Updated details for support for auto RDM over FC 

---

content/docs/csidriver/features/powermax.md

Update limitations for vSphere for PowerMax

Update limitations for vSphere for PowerMax

---

content/docs/_index.md
content/docs/replication/deployment/powerscale.md
content/docs/replication/release/_index.md

Cleaning up final odds and ends before release. Replication is moving to 1.3.1. 
| |

Cleanup for Replication Release 1.3.1

---

content/docs/replication/release/_index.md

Removed known issue #516 from Replication release notes because it is now a feature rather than a bug
| |

Removed Replication Known Issue from Release Notes

---

content/docs/authorization/troubleshooting.md

Updated Troubleshooting section for Authorization, issue being raised by failure of creating the karavi-authorization rpm through the 'make rpm' command.
|dell/csm#164 |

Rpm auth issue

---

config.toml
content/docs/_index.md
content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/offline/_index.md
content/docs/replication/migrating-volumes.md
content/v1/_index.md
content/v1/csidriver/features/powermax.md
content/v1/csidriver/installation/helm/powermax.md
content/v1/csidriver/installation/offline/_index.md
content/v1/replication/migrating-volumes.md
content/v1/resiliency/deployment.md
content/v2/_index.md
content/v2/csidriver/_index.md
content/v2/csidriver/features/powermax.md
content/v2/csidriver/installation/helm/powermax.md
content/v2/csidriver/release/powermax.md
content/v2/csidriver/upgradation/drivers/powermax.md
content/v2/replication/migrating-volumes.md

Release 1.3.1 changes
| https://github.com/dell/csm/issues/590 |

Release 1.3.1 changes

---

content/docs/csidriver/_index.md

Claiming Amazon EKS support for CSI PowerScale driver.
|https://github.com/dell/csm/issues/579|

Add Amazon EKS support to PowerScale

---

content/docs/replication/_index.md

BUG: https://github.com/dell/csm/issues/614
Updated the Replication Capabilities (Matrix Table) of PowerMax.
|https://github.com/dell/csm/issues/614|

Updated the Replication Capabilities of Power Max

---

content/docs/deployment/_index.md
content/docs/deployment/csminstallationwizard/index.md

Installation wizard documentation update

---

content/docs/csidriver/_index.md

- Updated MKE version to 3.6.x
| dell/csm#583 |

Added MKE 3.6.x support for PowerStore driver

---

content/docs/csidriver/_index.md

Updated EKS anywhere support status for Unity XT
|https://github.com/dell/csm/issues/621 |

Updating support status of Unity XT for EKS

---

content/docs/deployment/csmoperator/_index.md

Update support matrix in CSM Operator documentation
|  https://github.com/dell/csm/issues/583 |

Update support matrix in CSM Operator documentation

---

content/docs/csidriver/_index.md
content/docs/replication/_index.md

[Previous PR](https://github.com/dell/csm-docs/pull/444) included some commits that should not have made it into 1.6 as of yet. This PR is to revert the changes made by those commits. Also attached are screenshots from my local deployment. 
| [583 ](https://github.com/dell/csm/issues/583)|
| [597 ](https://github.com/dell/csm/issues/597)|

Reverted some changes that should not be in 1.6 branch

---

content/docs/csidriver/_index.md

Updated RKE to 1.4.1 for powerflex
| dell/csm#583

Powerflex documentation update: Added support for RKE 1.4.1

---

content/docs/csidriver/_index.md

Updated Docs for PowerStore 2.6.0
| |

Updated Docs for PowerStore 2.6.0

---

content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md

Changes for PowerStore v2.5.1
| https://github.com/dell/csm/issues/582 |

CSI-PowerStore v2.5.1 changes

---

content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/test/powermax.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/replication/high-availability.md

New Features updates for PowerMax 
| https://github.com/dell/csm/issues/646
https://github.com/dell/csm/issues/609 |

New Features updates for PowerMax 

---

content/docs/replication/_index.md
content/docs/replication/deployment/installation.md
content/docs/replication/deployment/powerflex.md
content/docs/replication/deployment/storageclasses.md
content/docs/replication/release/_index.md
content/docs/replication/replication-actions.md

Add the documentation related to enabling `Replication` on PowerFlex.
| https://github.com/dell/csm/issues/618  |

Powerflex Replication

---

content/docs/csidriver/_index.md

Updated support matrix for PowerStore with Anthos 1.13
| |

CSI-PowerStore: Anthos 1.13 support

---

content/v1/csidriver/release/powermax.md

Update known issues PowerMax

---

content/docs/deployment/csmoperator/modules/authorization.md

PR to update steps for installing authorization proxy server via csm operator.
| https://github.com/dell/csm/issues/633|

Update Authorization Steps for CSM Operator

---

content/docs/replication/architecture/_index.md
content/docs/replication/deployment/installation.md
content/docs/replication/uninstall.md
content/docs/replication/upgrade.md

Replication doc updates for CRD version update and module upgrade.
| https://github.com/dell/csm/issues/432 |

Replication doc updates for CRD version update and module upgrade

---

content/docs/snapshots/volume-group-snapshots/_index.md

This is a documentation update for volume group snapshots only. There is no feature change. Document updates include:
- Clarification for vgs installation instructions

updated vgs installation instructions for clarity

---

content/docs/references/cli/_index.md

Documentation update for dellctl driver includes:
- Update for dellctl volume get feature
| https://github.com/dell/csm/issues/408|

volume list changed to volume get

---

content/docs/deployment/csminstallationwizard/src/csm-versions/csm-1.5.0.properties
content/docs/deployment/csminstallationwizard/src/csm-versions/csm-1.6.0.properties
content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/css/style.css
content/docs/deployment/csminstallationwizard/src/static/js/commands.js
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/static/js/utility.js
content/docs/deployment/csminstallationwizard/src/templates/csm-values.template

Updated the CSM Installation Wizard code.
| dell/csm#591 |

Updated csm-installation-wizard code in csm-docs

---

content/docs/deployment/csminstallationwizard/index.md

Updated the csm-installation-wizard documentation page.
| dell/csm#591 |

Feature 591 csm-installation-wizard documentation page update

---

content/docs/references/cli/_index.md

Documentation update for dellctl driver includes:
- Update for dellctl volume get output ntoes
| https://github.com/dell/csm/issues/408|

added clarification for auth proxy version in volume get output

---

content/docs/resiliency/_index.md

Update CSM for Resiliency support matrix for kubernetes version.
| #https://github.com/dell/csm/issues/597 |

Update CSM for Resiliency support matrix for kubernetes version

---

content/docs/_index.md
content/docs/authorization/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/release/_index.md

PR to adjust Authorization versions for CSM release 1.5.1
|https://github.com/dell/csm/issues/582 |

Update CSM authorization for release 1.5.1

---

content/docs/csidriver/_index.md

Add the missing protocol in the access mode row
| |

Add NVMe to the compatible access mode

---

config.toml
content/docs/csidriver/release/powerstore.md

Release note - Powerstore
Config Toml
|https://github.com/dell/csm/issues/582|

Toml and Powerstore Release note change.

---

config.toml
content/docs/_index.md
content/docs/authorization/_index.md
content/docs/authorization/configuration/powerflex/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/release/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/references/cli/_index.md

PowerStore - Fixed issue where driver was not properly cleaning up resources when volumes were unmounted.
|https://github.com/dell/csm/issues/582|

CSM Docs v1.5.1 Changes - Release 1.5.1 to Main

---

content/docs/resiliency/_index.md
content/docs/resiliency/deployment.md
content/docs/resiliency/release/_index.md
content/docs/resiliency/upgrade.md

- Added documentation for feature Resiliency in Powerstore
- Updated release page for Resiliency
| dell/csm#587 |
| dell/csm#583 |

Documentation changes for Resiliency for PowerStore driver

---

content/docs/deployment/csminstallationwizard/index.md
content/docs/deployment/csminstallationwizard/src/index.html

Updated supported versions 
| dell/csm#591|

Feature 591 csm installtion wizard update documentation

---

content/docs/csidriver/installation/test/certcsi.md

Update the hyperlink refrences
|https://github.com/dell/csm/issues/628|
Test:

Update cert-csi docs

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powermax.md

Added support for mke  3.6 for powermax.
|https://github.com/dell/csm/issues/672 |

Updating MKE  3.6 support for powermax

---

content/docs/replication/_index.md

Updated the Replication support matrix to add PowerStore v3.0, v3.2, and v3.5 (Medusa), and PowerScale v9.4.
https://osj-sio-03-prd.cec.lab.emc.com/view/Phoenix_Team/job/CSM_Phoenix/job/CSM-pipeline-Phoenix/254/

Updated Storage Platforms version for Replication

---

content/docs/csidriver/_index.md

Added 1.26 Kubernetes version
Removed 1.23 Kubernetes version
| dell/csm#583

Powerflex documentation update: Added support for Kubernetes 1.26

---

content/docs/csidriver/_index.md

Updated Docs for RKE and SLES version support for PowerStore
|https://github.com/dell/csm/issues/583|

Updated RKE & SLES Versions for PowerStore

---

content/docs/deployment/csmoperator/modules/replication.md

Fix broken link in Operator install instructions for CSM Replication.
|[685 ](https://github.com/dell/csm/issues/685)|

Fix broken link in Operator install of Replication

---

content/docs/csidriver/installation/test/certcsi.md

updated command for docker build in cert-csi 
| dell/csm#628 |

docker command update in cert-csi document 

---

content/docs/_index.md
content/docs/observability/_index.md
content/docs/observability/deployment/_index.md
content/docs/observability/deployment/helm.md
content/docs/observability/deployment/offline.md
content/docs/observability/deployment/online.md
content/docs/observability/design/_index.md
content/docs/observability/metrics/powermax.md
content/docs/observability/release/_index.md
content/docs/observability/upgrade/_index.md

Documentation update for Observability 1.5 which includes:
- Update of support matrix
- Add document for PowerMax, metrics, installer, etc
- Release note update
|https://github.com/dell/csm/issues/583|

Document change for Observability 1.5

---

content/docs/resiliency/_index.md

| #https://github.com/dell/csm/issues/597 |

add note for non graceful node shutdown

---

content/docs/csidriver/installation/operator/_index.md
content/v1/csidriver/installation/operator/_index.md

Updated Document for Driver Upgrade using Operators
|https://github.com/dell/csm/issues/648 |

Updated Upgrade Documentation

---

content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md

Updating support matrix for CSI operators

---

content/docs/deployment/csmoperator/modules/replication.md

This PR is to address the review comment for replication readme.
|[490](https://github.com/dell/csm-docs/pull/490/files) |
|[431](https://github.com/dell/csm-docs/pull/431/files) |

Change few lines in replication readme

---

content/docs/csidriver/_index.md

Added MKE 3.5.X in support matrix

add the mke 3.5.x support for powerflex.

---

content/docs/authorization/configuration/proxy-server/_index.md

This PR fixes the arguments in karavictl commands.
|https://github.com/dell/csm/issues/583

Update proxy server configuration

---

content/docs/deployment/csmoperator/modules/_index.md

Fixing broken links with regards to installing the CSI drivers. We have updated links because we support multiple drivers.
|[685 ](https://github.com/dell/csm/issues/685)|

Fix broken links

---

content/docs/deployment/_index.md

Design Issue Fix
|https://github.com/dell/csm/issues/583|

Design Issue Fix - Supported Drivers and Module Information

---

content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/release/powerflex.md

This pr updates the doc changes related to Powerflex Automated Sdc Deployment.

Update the docs for Powerflex Automated sdc deployment

---

.github/workflows/linter.yaml
content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csminstallationwizard/src/csm-versions/csm-1.6.0.properties
content/docs/deployment/csminstallationwizard/src/index.html

Updated documentation page for installation wizard
| dell/csm#591|

Csm installation wizard doc update

---

content/docs/csidriver/release/operator.md

- Updated the release notes for operator

Update csi operator 1.11.0 release notes

---

content/docs/applicationmobility/deployment.md
content/docs/applicationmobility/release.md
content/docs/references/cli/_index.md

Update documentation for Application Mobility and Dell CLI for the 1.6.0 release.
- [N/A] Have you added high-resolution images?

Update release notes and versions for Application Mobility and dellctl

---

content/docs/applicationmobility/_index.md

Update application-mobility docs to add k8s v1.26 support.
| |

Update application-mobility docs to add k8s v1.26 support

---

content/docs/replication/_index.md

Updates to the replication support matrix for OpenShift 4.11.
|https://github.com/dell/csm/issues/583|

Updates to the replication support matrix for OpenShift 4.11.

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md

- Updates vSphere section for vCenter secrets
| https://github.com/dell/csm/issues/686|

CSI Powermax: Update vSphere section for secrets

---

content/docs/deployment/csminstallationwizard/src/csm-versions/csm-1.6.0.properties

updated image version

---

content/docs/csidriver/installation/operator/_index.md

- Fixing document review comments

CSI operator docs updates

---

content/docs/csidriver/_index.md
content/docs/release/_index.md

Documentation changes  for csm-operator

Documentation changes  for csm-operator

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/secure/encryption/_index.md
content/docs/secure/encryption/deployment.md
content/docs/secure/encryption/rekey.md
content/docs/secure/encryption/release.md

Update documentation for Encryption for the 1.6.0 release.
- [N/A] Have you added high-resolution images?

Encryption pre-release updates.

---

content/docs/replication/_index.md
content/docs/replication/upgrade.md

Removed a redundant support matrix for replication and made improvements to the upgrade page.
| |

Removing redundant replication support matrix and updating Upgrade page

---

content/docs/_index.md

Update image version to 0.3.0 on the main docs page for Encryption and App Mobility.
- [N/A] Have you added high-resolution images?

Updated image version for Encryption and App Mobility.

---

content/docs/csidriver/_index.md

Updated support matrix for CSI-PowerStore with Anthos 1.14 support

CSI-PowerStore: Anthos 1.14 support

---

content/docs/observability/troubleshooting/_index.md

Observability troubleshooting doc update

---

content/docs/references/FAQ/_index.md

Updated the Module information in FAQ
|https://github.com/dell/csm/issues/715|

Update the Module Information in FAQ

---

content/docs/references/FAQ/_index.md

Fixed Broken link in the Faq section
|https://github.com/dell/csm/issues/715|

Updated the Module information in FAQ

---

content/docs/resiliency/_index.md

Add support of unity version 5.2 and 5.3 for Resiliency.
| |

Update unity support matrix, adding 5.2 and 5.3

---

content/docs/csidriver/troubleshooting/powermax.md

updated troubleshooting documentation for PowerMax
|https://github.com/dell/csm/issues/750 |

updated troubleshooting documentation for PowerMax

---

content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/static/js/utility.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.6.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

Adding Unity driver to Installation Wizard UI.
| https://github.com/dell/csm/issues/698 |
- [] Did you add the examples wherever applicable?
- [] Have you added high-resolution images?

Adding UI changes for Unity driver

---

content/docs/replication/_index.md

This PR is to add the replication support for K8s 1.27.
|                      |
- [ X] Have you run a grammar and spell checks against your submission?

Updated Replication to support K8s 1.27

---

content/docs/replication/deployment/powerstore.md

Started documenting the addition of PowerStore File Replication. 
| [639](https://github.com/dell/csm/issues/639) |

PowerStore file replication support

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powermax.md
content/docs/replication/_index.md

Openshift 4.12 support for PowerMax
| https://github.com/dell/csm/issues/571|

Openshift 4.12 support for PowerMax

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powermax.md
content/docs/replication/_index.md

1. Added support for PowerMax v10.0.1 array
2. Migrated image registry from k8s.gcr.io to registry.k8s.io
| https://github.com/dell/csm/issues/760|
| https://github.com/dell/csm/issues/744|

Adding powermax 10.0.1 support

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powerstore.md

Updating CSI Powerstore support matrix to add support for OpenShift 4.12 and remove 4.10.
| https://github.com/dell/csm/issues/571|

Adding OpenShift 4.12 support for CSI Powerstore

---

config.toml
content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/upgradation/drivers/isilon.md

- Updated CSI PowerScale version from 2.6.0 to 2.6.1 and CSM version from 1.6.0 to 1.6.1
- Added Fixed issue (replication) to PowerScale driver.
| https://github.com/dell/csm/issues/753 |

Updating main with changes from release-1.6.1 (#570)

---

content/docs/csidriver/_index.md

Updated driver support matrix 
| https://github.com/dell/csm/issues/773 |

Updated driver support matrix 

---

content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/constants.js
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js

Adding release name for PowerFlex and Unity installation wizard
| https://github.com/dell/csm/issues/698 |

Adding release name for PowerFlex and Unity installation wizard

---

content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/constants.js
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/static/js/utility.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.6.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

Added Powerscale support from Installation Wizard UI
|https://github.com/dell/csm/issues/698 |

Feature 698 adding powerscale support

---

content/docs/observability/_index.md

PR to update observability support Powerstore 3.5 and K8S 1.27.
| https://github.com/dell/csm/issues/761|

PR to update observability support PowerStore 3.5

---

content/docs/replication/_index.md

Updating CSM Replication documentation to add support for PowerScale OneFS 9.5.

PowerScale OneFS 9.5 qualification for CSM Replication

---

content/docs/csidriver/_index.md

Added Support for k8s 1.27 in PowerStore.
|https://github.com/dell/csm/issues/761 |

Added Support for k8s 1.27 in PowerStore

---

content/docs/authorization/_index.md

Add Unisphere 10.0.1 support for Authorization and PowerMax.
|https://github.com/dell/csm/issues/743 |

[feature-743]: Add Unisphere 10.0.1 for Authorization

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/isilon.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md

|https://github.com/dell/csm/issues/751|

Updated deprecation notice of csi operator from csm docs

---

content/docs/observability/_index.md

| https://github.com/dell/csm/issues/571|

Update index to support observability open shift 4.12

---

config.toml
content/docs/references/cli/_index.md
layouts/partials/scripts.html

Added a copy button on syntax code blocks with prism in Reference's Pages. Modified the code-blocks as required for enabling the copy button.

copy-button-references

---

content/docs/replication/cluster-topologies.md
content/docs/replication/deployment/configmap-secrets.md
content/docs/replication/deployment/install-repctl.md
content/docs/replication/deployment/installation.md
content/docs/replication/deployment/powerflex.md
content/docs/replication/deployment/powermax.md
content/docs/replication/deployment/powerscale.md
content/docs/replication/deployment/powerstore.md
content/docs/replication/deployment/storageclasses.md
content/docs/replication/disaster-recovery.md
content/docs/replication/migration/migrating-volumes-diff-array.md
content/docs/replication/migration/migrating-volumes-same-array.md
content/docs/replication/upgrade.md

Added a copy button on syntax code blocks with prism in Replication Pages. Modified the code-blocks as required for enabling the copy button.

copy-button-on-replication-pages

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

Adding deprecation notice for removing linked proxy mode for Powermax
|https://github.com/dell/csm/issues/757 |

Adding deprecation notice for link proxy mode

---

content/docs/observability/_index.md

Add powermax OS 10.0.1 support for Observability.
| https://github.com/dell/csm/issues/743|

Add Observability Support  for powermax10.0.1

---

content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/powermax.md

Added kubernetes 1.27 support
Added changes related to CSM 1.7
| https://github.com/dell/csm/issues/743|
| https://github.com/dell/csm/issues/761|

Adding powermax support for k8_27

---

content/docs/_index.md

Deleted first support matrix from the main landing page of CSM-Docs
|https://github.com/dell/csm/issues/807|

bug_update_support_matrix

---

content/docs/applicationmobility/deployment.md
content/docs/applicationmobility/uninstallation.md
content/docs/applicationmobility/use_cases.md
content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/_index.md
content/docs/deployment/csmoperator/drivers/powerflex.md
content/docs/deployment/csmoperator/drivers/powerscale.md
content/docs/deployment/csmoperator/drivers/powerstore.md
content/docs/deployment/csmoperator/modules/authorization.md
content/docs/deployment/csmoperator/modules/observability.md
content/docs/deployment/csmoperator/modules/resiliency.md
content/docs/resiliency/_index.md
content/docs/resiliency/deployment.md
content/docs/resiliency/upgrade.md
content/docs/secure/encryption/rekey.md
content/docs/snapshots/volume-group-snapshots/_index.md

Added a copy button on syntax code blocks with prism in applicationmobility, deployment, resiliency, secure and snapshot pages. Modified the code-blocks as required for enabling the copy button.

copy-button-for-secure-snapshot-and-other-pages

---

content/docs/interactive-tutorial/_index.md
content/docs/interactive-tutorials/_index.md

Add Instruqt CSM lab

---

content/docs/csidriver/_index.md

Added kubernetes 1.27 support
| dell/csm#761

Adding Powerflex support for k8s1.27

---

content/docs/csidriver/release/powermax.md

Added support for read only access mode for raw block volumes
| https://github.com/dell/csm/issues/792 |

Added support for read only access mode for raw block volumes

---

content/docs/deployment/csmoperator/drivers/powerflex.md
content/docs/deployment/csmoperator/drivers/powerscale.md

Examples have broken indentation if we copy-paste from the doc
| |

Fix indentation

---

content/docs/deployment/csmoperator/modules/resiliency.md

Updated the resiliency module with latest sample file i.e. added 2 components under resiliency module section
|https://github.com/dell/csm/issues/739|

Resiliency sample

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/features/powermax.md
content/docs/csidriver/features/powerscale.md
content/docs/csidriver/features/powerstore.md
content/docs/csidriver/features/unity.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/isilon.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/installation/test/certcsi.md
content/docs/csidriver/installation/test/powermax.md
content/docs/csidriver/installation/test/powerscale.md
content/docs/csidriver/partners/tanzu.md
content/docs/csidriver/uninstall/_index.md
content/docs/csidriver/upgradation/drivers/isilon.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/csidriver/upgradation/drivers/unity.md

Added a copy button on syntax code blocks with prism in CSIDriver Pages. Modified the code-blocks as required for enabling the copy button.

copy-button-for-csidriver-pages

---

content/docs/replication/deployment/install-repctl.md
content/docs/replication/deployment/install-script.md
content/docs/replication/deployment/installation.md
content/docs/replication/uninstall.md

Replication installation doc corrections.
Separate pages for repctl vs script installation.
| https://github.com/dell/csm/issues/794 |

Replication installation doc corrections

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/unity.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/unity.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/_index.md
content/docs/deployment/csmoperator/drivers/unity.md
content/docs/deployment/csmoperator/release/_index.md

Added docs for CSI Unity install support in csm-operator
Also, update unity driver version from 2.6 to 2.7 wherever applicable
| https://github.com/dell/csm/issues/756 |

Add docs for CSI unity support in CSM Operator

---

content/docs/csidriver/installation/test/powermax.md
content/docs/csidriver/release/powermax.md

QoS parameters for throttling performance and bandwidth 
| https://github.com/dell/csm/issues/726 |

Doc support : QoS parameters for throttling performance and bandwidth 

---

content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/deployment/csmoperator/_index.md

Added the document changes for supporting csi-driver upgrade via csm-operator.
| https://github.com/dell/csm/issues/805 |

Added support for csi-driver upgrades via csm-operator

---

content/docs/deployment/csmoperator/modules/_index.md
content/docs/deployment/csmoperator/modules/observability.md

Update CSM Operator for PowerStore

Update CSM Operator for PowerStore

---

content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/deployment/csmoperator/_index.md

Reverting the changes in the main branch
| https://github.com/dell/csm/issues/805|

reverting the changes in the main branch

---

content/docs/replication/_index.md
content/docs/replication/deployment/install-repctl.md
content/docs/replication/deployment/install-script.md
content/docs/replication/deployment/installation.md
content/docs/replication/deployment/powerflex.md
content/docs/replication/deployment/powermax.md
content/docs/replication/deployment/powerscale.md
content/docs/replication/deployment/powerstore.md
content/docs/replication/release/_index.md
content/docs/replication/upgrade.md

Minor cleanup work in replication to prepare for 1.7.0 release.
|  -------------- |

Replication Cleanup

---

content/docs/deployment/csmoperator/modules/authorization.md

Update Operator Authorization installation steps with current release sample files. 
|https://github.com/dell/csm/issues/826 |

[bug-826]: Update authorization samples

---

content/docs/authorization/_index.md
content/docs/resiliency/_index.md

Updated k8s versions for Resiliency and Authorization 
Updated supported OpenShift version for Resiliency
Updated support matrix for Authorization

Updating k8s, openshift versions for resiliency and authorization and support matrix for authorization

---

content/docs/references/cli/_index.md

This pr updates the dellctl images documentation with the latest changes introduced in the dellctl images.
| https://github.com/dell/csm/issues/834 |

updated the docs for dellctl images.

---

content/docs/csidriver/_index.md

Updated Google Anthos support for PowerMax 
https://github.com/dell/csm/issues/743

Updated google anthos support

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powerstore.md
content/docs/deployment/csmoperator/drivers/powerstore.md

Release notes for CSI-PowerStore

Release notes for PowerStore

---

content/docs/csidriver/_index.md
content/docs/csidriver/features/powerscale.md
content/docs/csidriver/installation/operator/isilon.md
content/docs/csidriver/release/powerscale.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csmoperator/drivers/powerscale.md

- Updated quota limit feature details
- Updated supported anthos version
- Add `storageCapacity` description for operators
- Added `storageCapacity` parameter for csi-powerscale in 1.7.0 template.
|https://github.com/dell/csm/issues/742 |
|https://github.com/dell/csm/issues/824 |

Quota limit feature changes

---

content/docs/authorization/release/_index.md
content/docs/resiliency/release/_index.md

Update release notes for Resiliency and Authorization.
| #https://github.com/dell/csm/issues/743 |

Update release notes for Resiliency and Authorization

---

content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/modules/resiliency.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/resiliency/release/_index.md

Version update along with some new parameter introduced in helm table

Docs for CSI-PowerStore

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/upgradation/drivers/powerflex.md

This PR includes changes for doc updates for csi-powerflex v2.7.0 driver.

Powerflex v2.7.0 docs update

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

Added csi-metadata-retriever on CSM Installation Wizard deployment page.

CSI-PowerStore: Added csi-metadata-retriever for CSM Installation Wizard

---

content/docs/csidriver/installation/operator/_index.md

Update CSI PowerScale driver support matrix in CSI-Operator

Update PowerScale driver support matrix in CSI-Operator

---

content/docs/replication/deployment/powerflex.md
content/docs/replication/replication-actions.md

Address multiple suggestions for improvement in the PowerFlex Replication documentation.
| https://github.com/dell/csm/issues/817 |
| https://github.com/dell/csm/issues/818 |

Update PowerFlex replication instruction

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

|https://github.com/dell/csm/issues/698 |

Added enable/disable option to storage capacity tracking for Powerscale

---

content/docs/authorization/configuration/powerflex/_index.md
content/docs/deployment/csminstallationwizard/_index.md

Update Resiliency and Authorization sidecar image version.
|  #https://github.com/dell/csm/issues/743 |

Update Resiliency and Authorization sidecar image version

---

content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

|https://github.com/dell/csm/issues/698|

Csm installation wizard values.yaml update

---

content/docs/csidriver/installation/helm/isilon.md

Update PowerScale Driver Version to from `2.6.1` to `2.7.0`.

Update PowerScale Driver Version to 2.7.0

---

content/docs/references/cli/_index.md

This pr updates the dellctl images documentation to reflect the latest changes
|https://github.com/dell/csm/issues/834 |

updated the dellctl images docs.

---

content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

Fixed node selector issue and added toleration comments in csm installation wizard values.yaml template
| https://github.com/dell/csm/issues/698|

CSM Installation wizard fixed node selector issue and added toleration comments.

---

content/docs/replication/_index.md

Remove Supported CSI Drivers section from Replication documentation 1.7.0 release.
|[dell/csm#743](https://github.com/dell/csm/issues/743) |

Remove Supported CSI Drivers 

---

content/docs/references/cli/_index.md

fixes issue with dellctl docs 
| |

add suffix to cmd

---

content/docs/deployment/csmoperator/_index.md
content/v1/deployment/csmoperator/_index.md
content/v2/deployment/csmoperator/_index.md
content/v3/deployment/csmoperator/_index.md

This PR includes changes for the updates done for csm-operator support matrix.
| https://github.com/dell/csm/issues/863 |

csm-operator support matrix updated

---

content/docs/deployment/csmoperator/_index.md

Updates the Authorization version in the Operator Supported CSM Components table.
| https://github.com/dell/csm/issues/743|

[feature-743]: Update Operator Support Matrix with v1.7.0

---

content/docs/snapshots/volume-group-snapshots/_index.md

Requested by PPDM on VGS escalation 
| |

add doc enhancement for vgs

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/operator.md

Updated installation and release notes to indicate support

updated installation and release notes to indicate support

---

content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powerscale.md

Added csm-operator resiliency support in release notes for PowerScale & PowerFlex.

Updated release notes for PowerScale & PowerFlex

---

content/docs/csidriver/installation/helm/powerflex.md

Fix broken link

---

content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template

Fixed the cert manager issue in Installation Wizard and updated document
| |

Doc update and cert manager bug fix

---

content/docs/replication/deployment/install-script.md

Updated replication install doc for centralized helm charts migration.

Replication install doc update for centralized helm charts

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template

Add SCT to installation wizard PMax
| https://github.com/dell/csm/issues/876 |

Add SCT to installation wizard PMax

---

content/docs/csidriver/installation/helm/isilon.md

Update Health monitor section with steps to enable with existing driver OR
while upgrading the driver version.
| |

Health monitor enable steps

---

content/docs/observability/_index.md
content/docs/replication/_index.md

OpenShift 4.13 support  for replication and observability 
| https://github.com/dell/csm/issues/724|

Obs rep ocp

---

content/docs/resiliency/_index.md

Update resiliency support for OCP 4.13

---

config.toml
content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/deployment/_index.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/powerflex.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/release/_index.md

-  Updated csi-powerflex Version from 2.7.0 to 2.7.1
-  Updated CSM Version from 1.7.0 to 1.7.1
|https://github.com/dell/csm/issues/911  |

Added docs changes for 1.7.1 release 

---

config.toml
content/docs/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/upgradation/drivers/powerflex.md
content/docs/deployment/_index.md
content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csminstallationwizard/release_notes.md
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/constants.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.1-values.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/powerflex.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/release/_index.md

Added docs changes for v1.7.1 release
| https://github.com/dell/csm/issues/911 |

Added docs changes for 1.7.1 release

---

content/docs/authorization/_index.md

PR to update storage support matrix for authorization

Add powerscale 9.5 support

---

content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csminstallationwizard/release_notes.md
content/docs/deployment/csminstallationwizard/src/static/js/constants.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template

Added Operator support for PowerScale in CSM Installation Wizard UI.

Adding Operator Support for PowerScale in wizard

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/upgradation/drivers/isilon.md

Document changes for powerscale  using a centralized helm for driver installation
| https://github.com/dell/csm/issues/877|

Powerscale changes for centralize helm

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powermax.md

Updated Google Anthos support for PowerMax
| https://github.com/dell/csm/issues/937 |

Updated Google Anthos support for PowerMax

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template

Updated csi unity v2.8.0 changes

Updated csi unity v2.8.0 changes

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powerflex.md

Update supported OCP version by CSI-PowerFlex to 4.13

Update ocp version to 4.13: csi-powerflex

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/release/powermax.md

This feature specifies the maximum number of volumes that can be created on a node.
|https://github.com/dell/csm/issues/878|
- [] Did you add the examples wherever applicable?

Documentation changes related to volume limit feature PowerMax

---

content/docs/observability/_index.md
content/docs/replication/_index.md

Updated Replication & Observability doc to add support for kubernetes 1.28.0 

Add support for kubernetes 1.28.0 - Observability and Replication

---

content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template

Adding Support for modules (authorization, replication, observability) in PowerScale via operator in CSM Installation wizard.

PowerScale module operator support in Installation wizard

---

content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/release/powerflex.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
content/docs/deployment/csmoperator/drivers/powerflex.md
content/v1/csidriver/installation/helm/powerflex.md
content/v1/csidriver/installation/offline/_index.md
content/v1/deployment/csmoperator/drivers/powerflex.md
content/v2/csidriver/installation/offline/_index.md

This PR updates the CSI-Powerflex SDC version to 3.6.1

Update sdc to 3.6.1

---

content/docs/csidriver/_index.md

Added Support for k8s 1.28 in PowerStore.
| https://github.com/dell/csm/issues/947|

Added Support for k8s 1.28 in PowerStore

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/replication/_index.md
content/docs/replication/deployment/powermax.md
content/docs/replication/migration/migrating-volumes-diff-array.md
content/docs/replication/release/_index.md

File replication support for PowerMax
| https://github.com/dell/csm/issues/861 |

File replication support for PowerMax

---

content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/commands.js
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template

Replication installation wizard

---

content/docs/applicationmobility/deployment.md

Make clear that we need to do this twice
| |

Add precisions to the App Mobility

---

content/docs/csidriver/upgradation/drivers/operator.md

- Add deprecation notice to dell-csi-operator upgrade section
|https://github.com/dell/csm/issues/885|

Add deprecation notice to dell-csi-operator

---

content/docs/csidriver/features/powerstore.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/operator/powerstore.md

Added volume limits support in CSI Powerstore
|https://github.com/dell/csm/issues/876|

Volume limits support in CSI Powerstore

---

content/docs/csidriver/installation/test/certcsi.md
content/v1/csidriver/installation/test/certcsi.md

Updating config file for cert-csi.
|https://github.com/dell/csm/issues/914|

Config file update

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/installation/helm/powerflex.md

This PR includes updates for documentation related to NFS.
| https://github.com/dell/csm/issues/763 |

NFS documentation updated

---

content/docs/_index.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/offline/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/upgradation/drivers/powerstore.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/drivers/_index.md

CSI Powerstore 2.8.0 documentation changes.
|https://github.com/dell/csm/issues/885|

CSI Powerstore 2.8.0 documentation changes

---

content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.8.0.template

Removed arrayConnectivityConnectionLossThreshold from podmon-node in template files

Removed arrayConnectivityConnectionLossThreshold from podmon-node in template files

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/upgradation/drivers/isilon.md

Revert the changes in main

---

content/docs/deployment/csmoperator/_index.md

This PR
Updates offline install to include step for driver install
| https://github.com/dell/csm/issues/939 |

Update offline install to include step for driver install

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template

PR to uncomment resiliency controller and node arguments and update authorization and resiliency sidecar images for CSM 1.8.
| https://github.com/dell/csm/issues/959|

Uncomment Resiliency args for Installation Wizard

---

content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template

Replication Yaml creation enhancements 

---

content/docs/deployment/csmoperator/drivers/powerflex.md

This PR is to fix the indentation issue in powerflex install doc page
| (https://github.com/dell/csm/issues/885) |
Issue screenshots
--------------------------------------
after the fix:

Fix indentation issues in powerflex docs

---

content/docs/references/cli/_index.md

This pr updates the dellctl images docs for csm 1.8

Update docs for dellctl images

---

content/docs/csidriver/features/powerflex.md
content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/upgradation/drivers/powermax.md
content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/static/js/utility.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.8.0.template
content/docs/deployment/csmoperator/drivers/powerflex.md

NFS documentation updated for csi-powerflex.
How are the changes tested:
- NFS operations available for CSM 1.8 from installation wizard GUI
- PowerFlex driver installation with helm updated with secret samples for NFS:
- NFS volumes feature page updated:
- samples for secret, SC-nfs, values YAMLs updated:

csi-powerflex: NFS documentation updated

---

content/docs/deployment/csminstallationwizard/_index.md

CSM Installation Wizard: resiliency version updated in documentation
|https://github.com/dell/csm/issues/885 |

CSM Installation Wizard Doc resiliency version updated

---

content/docs/deployment/csmoperator/drivers/powerflex.md

this PR removes an incorrect line found 

remove incorrect line

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.8.0.template

Updated Installation Wizard template with new config for replication and observability modules.

Replication/Observability 1.6 updates for Installation Wizard

---

content/docs/csidriver/installation/helm/unity.md

Updated helm-charts version in Unity

Helm charts version update

---

content/docs/cosidriver/_index.md
content/docs/csidriver/_index.md
content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/observability/_index.md
content/docs/observability/deployment/online.md
content/docs/observability/upgrade/_index.md
content/docs/references/cli/_index.md
content/docs/replication/_index.md
content/docs/replication/release/_index.md

Revert support for Kubernetes 1.28 in CSM.
|https://github.com/dell/csm/issues/885|

Roll back documentation for Kubernetes support

---

content/docs/_index.md

Updated missed latest versions for drivers on module support matrix

Updated missed latest versions for drivers on module support matrix

---

content/docs/csidriver/_index.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/deployment/csmoperator/drivers/powerflex.md

Added CSI Driver for PowerFlex support for PowerFlex 4.5

Added PowerFlex 4.5 support

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powerstore.md

Correcting the support matrix for CSI Operator .

Fix csi operator support matrix

---

content/docs/csidriver/_index.md

Clean up table with Access Mode to be more accurate and readable.
Making SDNAS explicit pre-req for NFS with PowerMax.
Requested by several customers
| |

Cleanup table and explicit SDNAS support

---

content/docs/csidriver/_index.md

Updating CSI-Driver index page for CSI Spec v1.6
|https://github.com/dell/csm/issues/905|

CSI Spec v1.6

---

content/docs/csidriver/_index.md

Updating notes for host operating systems needing to align with what each storage platform supports.

Update support matrix

---

content/docs/_index.md
content/docs/authorization/deployment/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/troubleshooting.md
content/docs/authorization/uninstallation.md
content/docs/authorization/upgrade.md

Updated release for target deprecation of Authorization RPM.
| |

Update release version in deprecation notice

---

content/docs/_index.md
content/docs/authorization/configuration/proxy-server/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/design.md
content/docs/authorization/troubleshooting.md
content/docs/observability/deployment/online.md

Removed deprecation notice related karavictl
| |

Remove deprecation notice

---

content/docs/csidriver/installation/operator/_index.md
content/docs/csidriver/installation/operator/isilon.md
content/docs/csidriver/installation/operator/powerflex.md
content/docs/csidriver/installation/operator/powermax.md
content/docs/csidriver/installation/operator/powerstore.md
content/docs/csidriver/installation/operator/unity.md
content/docs/csidriver/release/operator.md
content/docs/csidriver/upgradation/drivers/operator.md
content/v1/csidriver/installation/operator/_index.md
content/v1/csidriver/installation/operator/isilon.md
content/v1/csidriver/installation/operator/powerflex.md
content/v1/csidriver/installation/operator/powermax.md
content/v1/csidriver/installation/operator/powerstore.md
content/v1/csidriver/installation/operator/unity.md
content/v1/csidriver/release/operator.md

Updated the steps for migrating from dell-csi-operator to csm-operator
| https://github.com/dell/csm/issues/996 |

Updated steps to migrate from CSI to CSM Operator

---

content/docs/csidriver/features/powermax.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/release/powermax.md

Removing linked proxy mode related deprecation notice and documentation for powermax.
|https://github.com/dell/csm/issues/991 |

Feature 991 remove linked proxy mode

---

content/docs/authorization/configuration/powerflex/_index.md
content/docs/authorization/configuration/powermax/_index.md
content/docs/authorization/configuration/powerscale/_index.md
content/docs/csidriver/installation/helm/isilon.md
content/docs/csidriver/installation/helm/powerflex.md
content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/csidriver/installation/helm/unity.md
content/docs/replication/deployment/powerflex.md
content/docs/replication/deployment/powermax.md
content/docs/replication/deployment/powerscale.md
content/docs/replication/deployment/powerstore.md
content/docs/replication/migration/migrating-volumes-diff-array.md
content/docs/resiliency/deployment.md
content/docs/secure/encryption/deployment.md

As part of the effort to centralize all the images in the same attribute, the documentation is updated with images and cleaned from other image references.
* KRV-12738

New helm images location

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.8.0.template

Adding volume name prefix in operator templates 
|https://github.com/dell/csm/issues/989 |

Adding volumename_prefix_operator

---

content/docs/csidriver/installation/operator/operator_migration.md
content/docs/csidriver/installation/operator/redhat.md

Created CSI to CSM migration page, and document steps for migration in OpenShift UI.
|https://github.com/dell/csm/issues/996 |

CSI to CSM migration OpenShift UI

---

content/docs/csidriver/installation/operator/operator_migration.md

Created CSI to CSM migration page, and document steps for migration.
|https://github.com/dell/csm/issues/996 |

CSI to CSM Operator Migration Steps

---

.github/workflows/unit-test-reporter.yaml
content/docs/_index.md
content/docs/authorization/configuration/proxy-server/_index.md
content/docs/authorization/deployment/_index.md
content/docs/authorization/deployment/rpm/_index.md
content/docs/authorization/design.md
content/docs/authorization/troubleshooting.md
content/docs/authorization/uninstallation.md
content/docs/authorization/upgrade.md
content/docs/observability/deployment/online.md
package-lock.json
package.json

At this point of time we have two branches: "Release 1.9" and "Release 1.9.0". We need to merge them together so we will have only one branch "Release 1.9.0".
| |

Merging "Release 1.9" to "Release 1.9.0"

---

content/docs/csidriver/installation/test/certcsi.md

Update the command used to build the cert-csi image. Related to PR: https://github.com/dell/cert-csi/pull/51
| https://github.com/dell/csm/issues/1031 |

Update command to build the cert-csi image

---

content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/constants.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilion-1.9.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.9.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.9.0.template

Update Install wizard that can generate values.yaml with 1.9 template.

Update Install Wizard for CSM 1.9.0

---

content/docs/deployment/csminstallationwizard/src/index.html
content/docs/deployment/csminstallationwizard/src/static/js/utility.js
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template

With the centralized `images` no need for a "repo" customization
| |

Remove custom repo

---

content/docs/applicationmobility/_index.md
content/docs/authorization/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Updated the supported platform and orchestrator versions.  Also removed OS dependencies.

Remove os dependencies

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.9.0.template

This PR updates PowerStore & PowerFlex driver version to 2.9.0 in helm and operator templates.

PowerStore & PowerFlex: Driver version update in Installation Wizard templates

---

content/docs/references/cli/_index.md

Update output of `dellctl images` command for CSM 1.9
| dell/csm#1012 |

Update output of 'dellctl images' command for CSM 1.9

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.9.0.template

Updated PowerMax driver version in installation wizard.

Updating powermax driver version

---

content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.7.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.8.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.9.0.template

Fixed volume-name-prefix in the CSM Installation Wizard for PowerStore
| https://github.com/dell/csm/issues/989|

Fixed volume-name-prefix in the Installation Wizard for PowerStore

---

content/docs/csidriver/installation/helm/isilon.md
content/docs/deployment/csmoperator/drivers/powerscale.md

Added notes to ensure session based authentication is enabled for PowerScale if the CSM Authorization is enabled.

Add notes for PowerScale Auth support

---

content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/deployment/csmoperator/troubleshooting/_index.md
content/docs/observability/deployment/helm.md
content/docs/observability/deployment/offline.md
content/docs/observability/deployment/online.md
content/docs/observability/release/_index.md
content/docs/observability/upgrade/_index.md

Updated the docs as per feedback from Celestial doc review
| https://github.com/dell/csm/issues/1012|

Implementing feedback from doc review

---

content/docs/deployment/csmoperator/modules/authorization.md

Update Authorization release scripts to 1.9.0
[dell/csm#1012|](https://github.com/dell/csm/issues/1012) |

Update Authorization release scripts to 1.9.0

---

content/docs/authorization/_index.md

Update CSM Authorization to support Powermax 10.1

Update Authorization support for Powermax 10.1

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md

Adding PowerMax 10.1(Laurel) support 
|https://github.com/dell/csm/issues/1062 |

Adding PowerMax 10.1 support

---

content/docs/troubleshooting/_index.md
content/v1/observability/troubleshooting/_index.md
content/v1/troubleshooting/_index.md
content/v2/observability/troubleshooting/_index.md
content/v2/troubleshooting/_index.md

- Updated known issue for Observability
- Updated trouble shooting link for csm-operator in main trouble shooting page
|https://github.com/dell/csm/issues/1019 |

Updated known issue and troubleshooting link

---

content/docs/deployment/csminstallationwizard/_index.md

Update csminstallation wizard index page  powermax

Updating installation wizard index

---

content/docs/deployment/csmoperator/modules/resiliency.md

Update CSM Operator Resiliency  1.8.0
[dell/csm#1012|](https://github.com/dell/csm/issues/1012) |

Update CSM Operator Resiliency 1.8.0

---

content/docs/observability/deployment/_index.md
content/docs/observability/deployment/operator.md
content/docs/replication/deployment/install-operator.md
content/docs/resiliency/deployment/_index.md
content/docs/resiliency/deployment/helm.md
content/docs/resiliency/deployment/operator.md

Added deployment information for modules via CSM Operator.
|https://github.com/dell/csm/issues/996|

Updated links to CSM Operator deployment for modules

---

content/docs/secure/encryption/_index.md
content/docs/secure/encryption/release/_index.md

Updated supported orchestrators/release notes for encryption to align with all other CSM components.

Update encryption docs

---

content/docs/deployment/_index.md

Update deployment page

---

content/docs/cosidriver/release/_index.md
content/docs/cosidriver/troubleshooting/_index.md
content/docs/cosidriver/uninstallation/_index.md
content/docs/cosidriver/upgrade/_index.md

Updated cosi documentation to be more consistent with other drivers
| |

update cosi docs structure

---

content/docs/csidriver/_index.md

Update the support matrix to align with the community validated process
|https://github.com/dell/csm/issues/1079 |

Community certified

---

content/docs/csidriver/_index.md

Update Support matrix with precisions on the OS
| |

Support matrix add precisions on the OS

---

content/docs/csidriver/installation/offline/_index.md
content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.9.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.9.0.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/modules/replication.md
content/docs/replication/deployment/install-repctl.md
content/docs/replication/deployment/install-script.md
content/docs/replication/release/_index.md
content/docs/replication/upgrade.md

Updates references of Replication to v1.7.0

Update version of Replication to v1.7.0

---

content/docs/csidriver/features/powermax.md
content/v1/csidriver/features/powermax.md

Adding File snapshot unsupported entry for PowerMax
| |

Adding File snapshot unsupported entry for PowerMax

---

content/docs/csidriver/_index.md

Updated PowerFlex version from 4.5 to 4.5.x.
| |

Updated PowerFlex version to 4.5.x

---

content/docs/csidriver/_index.md

Remove k3s debian to community supported
| |

Remove k3s debian to community supported

---

content/docs/csidriver/_index.md

Update PowerFlex version to 4.5.x
| |

Update PowerFlex version to 4.5.x

---

content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powerscale.md

|https://github.com/dell/csm/issues/1109 |

Removing issues not planned for 1.9.1

---

content/docs/deployment/csmoperator/release/_index.md

Updated csm operator release notes
| https://github.com/dell/csm/issues/1109 |

Update release notes for CSM Operator

---

content/docs/csidriver/_index.md

Update _MKE version
Updated the MKE and Kubernetes version.
|https://github.com/dell/csm/issues/1109|

MKE version update

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/powerstore.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Adding PowerStore  medusa plus(3.6) support for CSM .
| https://github.com/dell/csm/issues/1129|

Adding PowerStore medusa plus(3.6) support for CSM

---

content/docs/deployment/csmoperator/release/_index.md

Add known issues in the v1.4.1 version of operator.
| https://github.com/dell/csm/issues/1133|
| https://github.com/dell/csm/issues/1130|

Add known issues to CSM v1.9.1

---

content/docs/deployment/csmoperator/release/_index.md

Reverting known issues from main since it is fixed in 1.9.2. 
|https://github.com/dell/csm/issues/1130 |

Revert known issues from operator

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Update supported minor versions of PowerScale to include all minor versions greater than 9.5.0.4
| |

Update supported minor versions of PowerScale 9.5.0.x

---

content/docs/authorization/_index.md
content/docs/csidriver/_index.md
content/docs/observability/_index.md
content/docs/replication/_index.md
content/docs/resiliency/_index.md

Update support for all PowerScale 9.5.0.x minor versions
| |

Update support for all PowerScale 9.5.0.x minor versions

---

content/docs/deployment/helm/drivers/installation/powerflex.md

Updating prerequisite for Powerflex driver
|https://github.com/dell/csm/issues/1091|

Updating prerequisite for Powerflex driver

---

content/docs/csidriver/_index.md

Restore k3s on debian in the main support table
| |

Restore k3s on debian in the main support table

---

content/docs/deployment/helm/drivers/installation/powerflex.md

Updating doc for csi-powerflex
|https://github.com/dell/csm/issues/1091|

Updating doc for csi-powerflex

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.10.0-values.template
content/docs/snapshots/_index.md

Updating latest sidecar versions in installation wizard templates 
| https://github.com/dell/csm/issues/1091|

Updating latest sidecar versions

---

content/docs/csidriver/installation/helm/powermax.md
content/docs/csidriver/installation/helm/powerstore.md
content/docs/deployment/csmoperator/drivers/powerstore.md

Update Multipath details in prerequisites
| https://github.com/dell/csm/issues/1142 |

Update Multipath details in prerequisites

---

content/docs/interactive-tutorials/_index.md

This PR is fixing interactive tutorial overflow, by making the `<iframe>` responsive.

Make interactive tutorial responsive

---

content/docs/deployment/helm/modules/applicationmobility/_index.md

Update app mobility version
| https://github.com/dell/csm/issues/1091|

Update app mobility version

---

content/docs/deployment/csmoperator/release/_index.md

Add release notes for v1.4.3 operator
| no 1.9.3 GH issue yet |

operator 1.4.3 release notes

---

.github/CODEOWNERS

Updated code owners to fix invalid file error.
| |

Update code owner file

---

content/docs/securitypolicy/_index.md

 Updating security policy

---

content/docs/resiliency/uninstallation.md

Added steps for Resiliency uninstall without uninstalling driver, but through driver upgrade.
|https://github.com/dell/csm/issues/1091|

Add Resiliency uninstall steps

---

content/docs/deployment/csmoperator/release/_index.md

Add a fixed issue for the CSM v1.9.3 release of csm-operator
| https://github.com/dell/csm/issues/1171 |

Adding one more fixed issue for operator

---

content/docs/deployment/csmoperator/modules/observability.md
content/docs/deployment/csmoperator/release/_index.md

Added a known issue and doc updates to 1.10.0 but realized they apply to 1.9.3 as well.
Links to changes so they are easier to review: 
New page here: https://github.com/dell/csm-docs/blob/add-known-issue-193/content/docs/deployment/csmoperator/modules/observability.md
Added known issue here (second one down, about secrets): https://github.com/dell/csm-docs/blob/add-known-issue-193/content/docs/deployment/csmoperator/release/_index.md
| no 1.9.3 issue yet |

Add known issue and updated docs to 1.9.3 release

---

content/docs/deployment/csminstallationwizard/src/index.html

- Trying to avoid application of template to a html file
| |

Trying to avoid application of template to a html file

---

content/docs/deployment/csminstallationwizard/src/index.html
layouts/docs/baseof.html

- Fixing header footer issue for installation wizard
| https://github.com/dell/csm/issues/1165 |

Fixing header footer issue for installation wizard

---

content/docs/csidriver/_index.md

Update support for Amazon EKS
| https://github.com/dell/csm/issues/1177|

Update support for Amazon EKS

---

content/docs/cert-csi/_index.md

Updates cert-csi qualification process to be more clear and fix bug to show CSI PowerMax tab.
| |

Update cert-csi qualification process

---

content/docs/csidriver/installation/offline/_index.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/release/_index.md

Add two bugs and update versions for csm-operator v1.4.4 release.
|https://github.com/dell/csm/issues/1189|
|https://github.com/dell/csm/issues/1190|

Updates for csm-operator 1.4.4 release

---

content/docs/csidriver/features/unity.md

Snapshot ingestion procedure for CSI Unity Driver.
|https://github.com/dell/csm/issues/1206|

Snapshot ingestion procedure for CSI Unity Driver

---

content/docs/deployment/csmoperator/modules/authorization.md

Add notes about editing Operator sample files for non-authorization namespace.
|dell/csm#1205 |

Add notes about non-default namespace for Authorization and Operator

---

content/docs/authorization/release/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/v1/authorization/release/_index.md
content/v1/deployment/csmoperator/release/_index.md
content/v2/authorization/release/_index.md
content/v2/deployment/csmoperator/release/_index.md
content/v3/authorization/release/_index.md
content/v3/deployment/csmoperator/release/_index.md

Add dell/csm#1205 to known issues of Authorization and CSM Operator
| dell/csm#1205 |

Add dell/csm#1205 to known issues

---

content/docs/prerequisites/_index.md

Updating powermax support matrix
| |

Updating powermax support matrix

---

content/docs/csidriver/release/powerflex.md
content/docs/deployment/helm/drivers/installation/powerflex.md
content/docs/deployment/helm/drivers/upgrade/powerflex.md

This PR includes documentation changes for the PowerFlex issue 1210.
| [#1210](https://github.com/dell/csm/issues/1210) |

Update Docs for PowerFlex issue 1210

---

content/docs/deployment/helm/drivers/installation/isilon.md
content/docs/deployment/helm/drivers/installation/powerflex.md
content/docs/deployment/helm/drivers/installation/unity.md
content/docs/deployment/helm/drivers/upgrade/isilon.md
content/docs/deployment/helm/drivers/upgrade/powerflex.md
content/docs/deployment/helm/drivers/upgrade/unity.md
content/v1/csidriver/installation/helm/isilon.md
content/v1/csidriver/installation/helm/powerflex.md
content/v1/csidriver/installation/helm/unity.md
content/v1/csidriver/upgradation/drivers/isilon.md
content/v1/csidriver/upgradation/drivers/powerflex.md
content/v1/csidriver/upgradation/drivers/unity.md
content/v2/csidriver/installation/helm/isilon.md
content/v2/csidriver/installation/helm/powerflex.md
content/v2/csidriver/installation/helm/unity.md
content/v2/csidriver/upgradation/drivers/isilon.md
content/v2/csidriver/upgradation/drivers/powerflex.md
content/v2/csidriver/upgradation/drivers/unity.md

Update helm-charts-version flag for powerflex, powerscale & unity.
| https://github.com/dell/csm/issues/1218 |

Update helm-charts-version flag

---

content/docs/_index.md
content/docs/deployment/csmoperator/_index.md

Temporary Notification about maintenance for CSM Operator users installing/upgrading CSM Operator via OCP UI.
| |

Operator unavailablity message for fresh install and upgrade in OCP UI

---

content/docs/_index.md
content/docs/deployment/csmoperator/_index.md

Revert "Operator unavailablity message for fresh install and upgrade in OCP UI"

---

content/docs/prerequisites/_index.md

Updating support for Powerstore 3.6
|https://github.com/dell/csm/issues/1129 |

Updating support for Powerstore 3.6

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.10.1-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.3-values.template

PowerFlex & Unity: Add podmon arguments in Installation Wizard templates
| https://github.com/dell/csm/issues/1270 |

PowerFlex & Unity: Add podmon arguments in Installation Wizard templates

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template

PowerFlex & Unity: Add podmon arguments in Installation Wizard templates in 1.11 template
| https://github.com/dell/csm/issues/1270 |

PowerFlex & Unity: Add podmon arguments in Installation Wizard templates in 1.11 template

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.10.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.3-values.template

Adding podmon entries for PowerStore in helm templates 
|https://github.com/dell/csm/issues/1270 |

Adding podmon entries for PowerStore

---

.github/CODEOWNERS
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.10.1-values.template
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.3-values.template

PowerScale: Add podmon arguments in Installation Wizard templates
| https://github.com/dell/csm/issues/1270 |

PowerScale: Add podmon arguments in Installation Wizard templates

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template

Powerscale 2.11.0 : Add podmon arguments in Installation Wizard templates
| https://github.com/dell/csm/issues/1270 |

Powerscale 2.11.0 : Add podmon arguments in Installation Wizard templates

---

config.toml
content/docs/authorization/configuration/powerflex/_index.md
content/docs/authorization/configuration/powermax/_index.md
content/docs/authorization/configuration/powerscale/_index.md
content/docs/authorization/release/_index.md
content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.11.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.11.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.11.0.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/modules/replication.md
content/docs/deployment/csmoperator/modules/resiliency.md
content/docs/deployment/helm/modules/installation/replication/install-repctl.md
content/docs/deployment/helm/modules/installation/replication/install-script.md
content/docs/deployment/helm/modules/upgrade/observability.md
content/docs/deployment/helm/modules/upgrade/replication.md
content/docs/deployment/offline/drivers/_index.md
content/docs/observability/release/_index.md
content/docs/resiliency/release/_index.md

update latest versions for drivers and modules
| https://github.com/dell/csm/issues/1221|

Update Latest Versions For `Drivers` & `Modules`

---

content/docs/csidriver/features/unity.md

Update Unity NAT feature section with a note that Unity NAT is not supported for management IP.
| https://github.com/dell/csm/issues/1279 |

Update Unity NAT feature section

---

content/docs/deployment/csmoperator/modules/authorization.md

This PR updates parameters in the custom resource and removes the step to create certificates since certificates are automatically created during deployment.
| https://github.com/dell/csm/issues/1281|

Update Authorization deployment for CSM Operator

---

content/docs/secure/encryption/_index.md
content/docs/secure/encryption/release/_index.md
content/v1/secure/encryption/_index.md
content/v1/secure/encryption/release/_index.md

Issue with Installation of Encryption
|https://github.com/dell/csm/issues/1309|

Encryption Release notes

---

content/docs/prerequisites/_index.md

Add note for OCP support for CSM Authorization.

Add note for OCP support for CSM Authorization

---

.github/workflows/actions.yaml

Updated malware check to trigger on release branch targeted PRs
| |

Updated malware check to trigger on release branch targeted PRs

---

content/docs/prerequisites/_index.md

Authorization support for Unit was marked as supported when that is not the case. Updates made to the prerequisites table.
| |

Update Authorization support for Unity

---

content/docs/prerequisites/_index.md

Resolve conflicts
| https://github.com/dell/csm/issues/1280 |

Resolve conflicts

---

content/docs/applicationmobility/release/_index.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/deployment/csminstallationwizard/release/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/replication/release/_index.md

Update the versions for CSI Drivers and Modules in Release Notes for release-1.11.0

Updated the release notes

---

content/docs/deployment/csmoperator/_index.md
content/docs/deployment/csmoperator/modules/observability.md

Add observability upgrade support documentation in dell documentation

Add observability upgrade support documentation

---

content/docs/deployment/csmoperator/drivers/powerflex.md

Update PowerFlex Deployment Guide link in Operator
| https://github.com/dell/csm/issues/1318 |

Update PowerFlex Deployment Guide link in Operator

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/offline/drivers/_index.md
content/docs/snapshots/_index.md

Update sidecar images to latest released version.

Update sidecar images to latest released version

---

content/docs/deployment/csmoperator/drivers/powerflex.md

Fixing sample link
|https://github.com/dell/csm/issues/1319|

Fixing sample link

---

content/docs/deployment/csmoperator/_index.md
content/docs/prerequisites/_index.md

* Update CSM-Operator version to 1.6.0
* Update image versions

Update CSM Operator version and images

---

content/docs/deployment/csmoperator/modules/authorization.md

Add certificate fields to Vault configuration.
| https://github.com/dell/csm/issues/1281|

Add certificate fields to Vault configuration

---

content/docs/prerequisites/_index.md

Update note to state that CSM Authorization v1 is not supported on OCP but v2 is.
|https://github.com/dell/csm/issues/1221 |

Update CSM Authorization note about OCP

---

content/docs/authorization/v2.0 Tech Preview/configuration/powerflex/_index.md

Updated configVersion in example and added note explaining the mismatch between image and config versions.
|https://github.com/dell/csm/issues/1281|

Add note on Authorization 2.0 Tech Preview configuration

---

content/docs/deployment/csmoperator/drivers/powerflex.md
content/v1/deployment/csmoperator/drivers/powerflex.md
content/v2/csidriver/installation/operator/powerflex.md
content/v2/deployment/csmoperator/drivers/powerflex.md
content/v3/csidriver/installation/operator/powerflex.md
content/v3/deployment/csmoperator/drivers/powerflex.md

Fixing Powerflex driver's Secret indentation
|https://github.com/dell/csm/issues/1355|

Fixing Secret indentation

---

content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/deployment/helm/drivers/installation/powermax.md

Updates Prereq for NVMe CSI Powermax
|https://github.com/dell/csm/issues/1221|

Updates Prereq for NVMe CSI Powermax

---

content/docs/prerequisites/_index.md

OCP 4.16 support
|https://github.com/dell/csm/issues/1359|

OCP 4.16 support

---

content/docs/replication/tools.md
content/v1/replication/tools.md
content/v2/replication/tools.md
content/v3/replication/tools.md

This will add a note in replication module that CA certificate is required when using '--use-sa' flag.
| dell/csm#1294 |

Update repctl inject docs

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js

Added Powerscale topology
| https://github.com/dell/csm/issues/1339 |

Added Powerscale topology

---

layouts/partials/head.html

Local deployment of CSM-docs was not working. This PR adds head.html which solves the error.
|dell/csm#1371 |

Fix for local deployment

---

content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js

Updated Unit tests
|https://github.com/dell/csm/issues/1339|

Unit tests updated in Installation Wizard

---

content/docs/support/cert-csi/_index.md
content/v1/csidriver/installation/test/certcsi.md

Updating the steps to download cert-csi and use it as a stand alone binary
|https://github.com/dell/csm/issues/1383|

Updating the steps to download cert-csi

---

content/docs/support/cert-csi/qualified.md

This PR updates `Community Qualified Configurations` table
| https://github.com/dell/csm/issues/1221|

Updated Community Qualifications

---

content/docs/deployment/helm/drivers/installation/isilon.md

- PowerScale driver needs zone readonly privilege to query zone endpoint operation while performing snapshot related operations.
|https://github.com/dell/csm/issues/1359|

update zone privilege for powerscale

---

content/docs/prerequisites/_index.md

Adding support powerscale 9.7 array
|https://github.com/dell/csm/issues/1398 |

Adding support powerscale 9.7 array

---

content/docs/prerequisites/_index.md

| https://github.com/dell/csm/issues/1399 |

Update Unity 5.4

---

content/docs/secure/encryption/release/_index.md

Revert Encryption Release notes
|https://github.com/dell/csm/issues/1221|

Revert Encryption Release notes

---

content/docs/cosidriver/features/objectscale.md
content/docs/deployment/helm/modules/installation/applicationmobility/_index.md

Updated the bucket yaml file in the cosi driver
|https://github.com/dell/csm/issues/1221 |

updated the cosi driver bucket yaml file

---

content/docs/deployment/offline/drivers/_index.md

Clean up output for offline bundle creation to remove version specific examples
| [1221](https://github.com/dell/csm/issues/1221) |

Clean up output for offline bundle creation to remove version specific examples

---

content/docs/secure/encryption/release/_index.md

Updated Encryption 0.6.0 release notes.

---

.github/workflows/deploy.yml

This is a stop gap measure to disable automatic publish when pushing to main. This action needs to be properly removed
This is a stop gap measure to disable automatic publish when pushing to main.n. This action needs to be properly removed
| |

Disabling automatic publish on push to main

---

.github/workflows/deploy.yml

Updating the deploy.yaml file will enable the automatic publish for the release-1.11.0 on push.
| |

Enabling automatic publish on push to release-1.11.0

---

.github/workflows/deploy.yml

Fix for the indentation issue in deploy.yaml file in workflows.
| |

Fix for deploy.yml in workflows

---

content/docs/deployment/helm/drivers/installation/powerflex.md

Fix for the indentation issue in the powerflex.md file
| |

Fix for powerflex.md file

---

.github/workflows/deploy.yml

Fix for the automatic publish in release-1.11.0
| |

Fix for autopublish in release-1.11.0

---

content/docs/support/cert-csi/qualified.md

Added https://github.com/dell/csm/issues/1442 & https://github.com/dell/csm/issues/1441
| https://github.com/dell/csm/issues/1442 |
| https://github.com/dell/csm/issues/1441 |

Updated community qualification

---

content/docs/csidriver/_index.md
content/docs/csidriver/release/unity.md
content/docs/deployment/csminstallationwizard/_index.md
content/docs/deployment/csmoperator/_index.md
content/docs/deployment/helm/drivers/installation/unity.md
content/docs/deployment/helm/drivers/upgrade/unity.md
content/docs/prerequisites/_index.md
content/v1/csidriver/release/unity.md

Updated docs for CSI-Unity 2.12
| https://github.com/dell/csm/issues/1435

Updated docs for CSI-Unity 2.12

---

content/docs/support/cert-csi/_index.md

This PR updates the driver capabilities in cert-csi samples 
|https://github.com/dell/csm/issues/1428 |

Updated driver capabilities in cert-csi samples

---

content/docs/resiliency/_index.md

1. Resiliency support for K8S 1.31 and OCP 4.17
| https://github.com/dell/csm/issues/1435 |

docs: Resiliency support for K8S 1.31 and OCP 4.17

---

content/docs/authorization/v2.0 Tech Preview/configuration/proxy-server/_index.md

Update the Authorization 2.0 documentation to address customer feedback.
|https://github.com/dell/csm/issues/1435|

Auth 2.0 documentation clarification

---

content/docs/deployment/helm/drivers/installation/powerflex.md

Add new section to PowerFlex CSI driver helm chart installation to include new parameter for enabling/disabling the SDC.
| https://github.com/dell/csm/issues/663 |

Added documenation for enabling/disabling the SDC installation with Powerflex helm charts

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.12.0-values.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.12.0.template
content/docs/deployment/helm/modules/upgrade/observability.md

1. Added operator template for csm 1.12
2. updated podmon and replication version in installation wizard
3. updated observability version in installation wizard
4. Helm chart changes addressed in https://github.com/dell/helm-charts/pull/504
|https://github.com/dell/csm/issues/1435|
- [] Did you add the examples wherever applicable?

updated podmon version in installation wizard

---

content/docs/support/cert-csi/qualified.md

This PR adds a new community contribution submitted in https://github.com/dell/csm/issues/1456. 
|https://github.com/dell/csm/issues/1456|

Update community contribution for OKE 4.14 on PowerFlex 2.11

---

content/docs/replication/_index.md
content/docs/replication/architecture/_index.md

Replication docs updated w.r.t. multiple drivers configured in a single cluster.
| https://github.com/dell/csm/issues/1445 |

KRV-28173: replication docs updated

---

hugo.toml

Enabling light/dark mode menu in the navbar
|https://github.com/dell/csm/issues/1476 |

Enabling light/dark mode menu

---

content/v1/replication/_index.md
content/v1/replication/architecture/_index.md
content/v2/replication/_index.md
content/v2/replication/architecture/_index.md
content/v3/replication/_index.md
content/v3/replication/architecture/_index.md

Replication docs updated w.r.t. multiple drivers configured in a single cluster.
Follow up changes to https://github.com/dell/csm-docs/pull/1261
| https://github.com/dell/csm/issues/1445 |

Replication docs updated

---

content/docs/deployment/csmoperator/drivers/powerflex.md

Update document for Operator deployment for powerflex with optional SDC. 
| https://github.com/dell/csm/issues/663|
- [] Did you add the examples wherever applicable?

Make SDC optional for powerflex deployment

---

content/docs/authorization/Migration guide from v1 to v2/_index.md

Minor grammar changes. Add Prerequisites section for using dellctl to get each tenant's volumes.
|https://github.com/dell/csm/issues/1281 |

[feature-1281]: Update Authorization migration

---

content/docs/deployment/csminstallationwizard/src/package.json

Updated csm-installation-wizard package name 
|https://github.com/dell/csm/issues/1478|

Update csm-installation-wizard package name

---

content/v1/deployment/csminstallationwizard/src/package.json
content/v2/deployment/csminstallationwizard/src/package.json
content/v3/deployment/csminstallationwizard/src/package.json

Updated csm-installation-wizard package name
|https://github.com/dell/csm/issues/1478|

updated installation wizard package name

---

content/docs/deployment/csmoperator/drivers/powerstore.md
content/docs/deployment/helm/drivers/installation/powerstore.md
content/v1/deployment/csmoperator/drivers/powerstore.md
content/v1/deployment/helm/drivers/installation/powerstore.md
content/v2/deployment/csmoperator/drivers/powerstore.md
content/v2/deployment/helm/drivers/installation/powerstore.md
content/v3/csidriver/installation/helm/powerstore.md
content/v3/deployment/csmoperator/drivers/powerstore.md

Update the PowerStore install sections to include NVMe settings that are crucial to access PowerStore arrays. Sections were added to the Helm and Operator install sections for configuration of multipathing and for reliable connectivity during NDU upgrades of PowerStore software.
The steps were reviewed by Dan Cohen, the submitter of issue 1459. The steps were also tested in the PowerStore QA lab and was shown to work for NDUs.
Refer to PR https://github.com/dell/csm-docs/pull/1280 for the original work to release 2.11.1.
| https://github.com/dell/csm/issues/1459 |

Update docs for PowerStore NVMe (main)

---

content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.12.0-values.template

Update the templates for the installation wizard to match the helm-chart updates.
| https://github.com/dell/csm/issues/1281 |

Update installation wizard template

---

content/docs/deployment/csmoperator/drivers/powerstore.md
content/docs/deployment/helm/drivers/installation/powerstore.md
content/v1/deployment/csmoperator/drivers/powerstore.md
content/v1/deployment/helm/drivers/installation/powerstore.md
content/v2/csidriver/installation/helm/powerstore.md
content/v2/deployment/csmoperator/drivers/powerstore.md
content/v3/csidriver/installation/helm/powerstore.md

Update the PowerStore install sections to include NVMe settings that are crucial to access PowerStore arrays. Sections were added to the Helm and Operator install sections for configuration of multipathing and for reliable connectivity during NDU upgrades of PowerStore software.
The steps were reviewed by Dan Cohen, the submitter of issue 1459. The steps were also tested in the PowerStore QA lab and was shown to work for NDUs.
|https://github.com/dell/csm/issues/1459 |

Update docs for PowerStore NVMe (release 2.11.1)

---

package-lock.json
package.json

updated csm-docs package name
| https://github.com/dell/csm/issues/1478|

Update csm-docs package name

---

content/docs/applicationmobility/_index.md
content/docs/applicationmobility/release/_index.md
content/docs/prerequisites/_index.md

This PR is addressing Application mobility documentation changes.
|https://github.com/dell/csm/issues/1478|

Updated Application mobility changes in 1.11.1

---

content/docs/deployment/csmoperator/_index.md
content/docs/deployment/offline/drivers/_index.md

Updated new prereq for CSM Operator offline bundle creation
| https://github.com/dell/csm/issues/1435|

Updated new prereq for CSM Operator offline bundle creation

---

content/docs/prerequisites/_index.md

This PR is to address the Support for OpenShift Virtualization 4.17 
and remove support for RKE, Google Anthos, VMware Tanzu
|https://github.com/dell/csm/issues/1508 |

OpenShift Virtualization and remove RKE, Google Anthos, VMware Tanzu

---

content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.10.2.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.11.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.10.2.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.11.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.10.2.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.11.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.12.0.template

Per the listed Issue, templates in the install wizard were not providing sidecars in some cases. This PR is an effort to go and add all appropriate sidecars to relevant templates in the Wizard, as well as update images in containers therein to be more accurate. 
| https://github.com/dell/csm/issues/1470 |

Install Wizard Templates - Added Sidecars/Images

---

content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js

Fix the Installation wizard Powermax resiliency checkbox issue
| https://github.com/dell/csm/issues/1540 |

Bugfix: Fix Installation wizard Powermax Resiliency Issue

---

content/docs/cosidriver/_index.md

This PR updates the notice for ObjectScale 1.2.x EOSS as announced in the Dell Support documentation. 
|https://github.com/dell/csm/issues/1435|

Update ObjectScale 1.2.x End of Standard Support notice for COSI

---

.github/workflows/deploy.yml
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/csidriver/release/unity.md
content/docs/deployment/csminstallationwizard/release/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/observability/release/_index.md
content/docs/replication/release/_index.md
content/docs/resiliency/release/_index.md

Update GH action for deploy.yaml
|https://github.com/dell/csm/issues/1435 |

Update GH action for deploy.yaml

---

content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/deployment/helm/drivers/installation/powermax.md
content/v1/deployment/csmoperator/drivers/powermax.md
content/v1/deployment/helm/drivers/installation/powermax.md
content/v2/deployment/csmoperator/drivers/powermax.md
content/v2/deployment/helm/drivers/installation/powermax.md
content/v3/deployment/csmoperator/drivers/powermax.md
content/v3/replication/deployment/powermax.md

Clarifying documentation for replication with regard to CSI-PowerMax.
Adding information to clarify the need for two locally connected storage systems for use with CSM Replication.
| https://github.com/dell/csm/issues/1435 |

Clarify PowerMax requirements for Replication

---

content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/deployment/helm/drivers/installation/powermax.md
content/v1/deployment/csmoperator/drivers/powermax.md
content/v1/deployment/helm/drivers/installation/powermax.md
content/v2/deployment/csmoperator/drivers/powermax.md
content/v2/deployment/helm/drivers/installation/powermax.md
content/v3/deployment/csmoperator/drivers/powermax.md
content/v3/replication/deployment/powermax.md

Pulling changes from release-1.12.0 to main.
| https://github.com/dell/csm/issues/1435 |

Include doc changes from release 1.12.0

---

content/docs/deployment/helm/drivers/installation/powerflex.md
content/v1/deployment/helm/drivers/installation/powerflex.md
content/v2/deployment/helm/drivers/installation/powerflex.md
content/v3/csidriver/installation/helm/powerflex.md

Update in documentation for PowerFlex nasName as required field for all CSM-docs versions.
|dell/csm#1562|

Update in documentation for PowerFlex nasName field

---

content/docs/replication/_index.md

Update Note for Snapshot not supported for replicated SyncIQ volumes by PowerScale driver
|https://github.com/dell/csm/issues/1487 |

Update Note for Snapshot not supported for replicated SyncIQ volumes by PowerScale driver 

---

content/docs/replication/_index.md

Update Note for Snapshot not supported for replicated SyncIQ volumes by PowerScale driver
| https://github.com/dell/csm/issues/1487 |

Update Note for Snapshot not supported for replicated SyncIQ volumes by PowerScale driver

---

content/docs/csidriver/features/powermax.md

Cert manager version update
| https://github.com/dell/csm/issues/1593|

Powermax prerequisite: cert-manager version update

---

content/docs/deployment/csmoperator/_index.md

updated driver upgrade command
|https://github.com/dell/csm/issues/1588 |

updated driver upgrade command

---

content/docs/deployment/csmoperator/_index.md

Recommended mode for operator upgrade updated 
| |

Recommended mode for operator upgrade updated 

---

content/docs/deployment/csmoperator/_index.md

updating the operator upgrade mode details

---

content/docs/deployment/csmoperator/modules/replication.md
content/v1/deployment/csmoperator/modules/replication.md
content/v2/deployment/csmoperator/modules/replication.md
content/v3/deployment/csmoperator/modules/replication.md

Updated documentation for the repctl command to inject clusters one at a time.
| |

Repctl doc change

---

content/docs/csidriver/features/powerflex.md
content/v1/csidriver/features/powerflex.md
content/v2/csidriver/features/powerflex.md
content/v3/csidriver/features/powerflex.md

Update content for NFS volume size round rules in PowerFlex driver.
|https://github.com/dell/csm/issues/1608 |

Update content for the volume size round rules

---

content/docs/csidriver/features/powerflex.md

Add documentation for PowerFlex Multi Availability Zone
| https://github.com/dell/csm/issues/1612 |

Add documentation for PowerFlex Multi Availability Zone

---

content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.11.1.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.13.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.11.1.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.13.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.11.1.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.12.0.template
content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.13.0.template

This PR made modifiable values in CSM installation wizard values.yaml consistent across drivers
| https://github.com/dell/csm/issues/1647|

Modifiable values consistent across drivers

---

.github/workflows/broken-links.yaml

Update action version for Hugo to fix broken link checker
| |

Update action version for hugo

---

content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/deployment/helm/drivers/installation/powermax.md

subjectAltName changes for reverse proxy cert validation
| https://github.com/dell/csm/issues/1571 |
Preview:

subjectAltName changes for reverse proxy cert validation

---

content/docs/deployment/csmoperator/drivers/powerstore.md

The sample multipath.conf has been changed to be more comprehensive config file.
| https://github.com/dell/csm/issues/1627 |

Add more comprehensive multipath.conf for PowerStore

---

content/docs/deployment/csmoperator/drivers/powermax.md

Prefix with 99- the PowerMax MachineConfig sample for multipathing
| https://github.com/dell/csm/issues/1618 |

Adjust the PowerMax MachineConfig 

---

content/docs/_index.md
layouts/shortcodes/message.html

This PR for updating the new link for the beta doc from  https://github.com/dell/csm-docs
|https://github.com/dell/csm/issues/1559 |

Update new beta doc link

---

.github/workflows/deploy.yml

Update the v0.141.0   hugo version
|https://github.com/dell/csm/issues/1559 |

Update the Hugo v0.141.0 version 

---

content/docs/support/cert-csi/_index.md

Updating Cert-CSI Version
|https://github.com/dell/csm/issues/1710 |

CERT-CSI Version Fix

---

content/docs/authorization/v1.x/release/_index.md
content/docs/authorization/v2.x/release/_index.md
content/v1/authorization/v1.x/release/_index.md
content/v1/authorization/v2.x/release/_index.md

Remove Powerstore from Authorization Release Notes as Authorization is not supported with Powerstore 
|https://github.com/dell/csm/issues/1722|

Remove Powerstore from Authorization Release Notes

---

content/docs/deployment/csmoperator/drivers/powermax.md
content/docs/deployment/helm/drivers/installation/powermax.md

Add documentation for creating the certificate Secret for PowerMax
| |

Add documentation for creating the certificate Secret for PowerMax

---

content/docs/supportmatrix/_index.md
content/v1/prerequisites/_index.md

Updates Prerequisites with OpenShift Virtualization tables for platforms and modules.
|https://github.com/dell/csm/issues/1765 |

[bug-1765]: Add OpenShift Virtualization tables for platforms and modules

---

content/docs/concepts/csidriver/features/powermax.md

This PR updates the priority of CSI PowerMax driver when its set to Auto
|https://github.com/dell/csm/issues/1689 |

Updated PowerMax Documentation

---

content/docs/concepts/cosidriver/_index.md
content/docs/concepts/cosidriver/features/objectscale.md
content/v1/cosidriver/_index.md
content/v1/cosidriver/features/objectscale.md

|https://github.com/dell/csm/issues/1772|

Broken link fix

---

content/docs/getting-started/installation/openshift/powermax/prerequisite/_index.md
content/docs/getting-started/installation/openshift/unityxt/prerequisite/_index.md
go.sum

Add MachineConfig in Unity Prerequisite (OpenShift) and simplified PowerMax Prerequisite in context of Openshift
|https://github.com/dell/csm/issues/1761|

Update Powermax and Unity Prerequisite

---

content/docs/concepts/replication/_index.md
content/v1/replication/_index.md

Removed Sync IQ note related to https://github.com/dell/csi-powerscale/pull/355
|https://github.com/dell/csm/issues/1487 |

Removed Sync IQ note

---

content/docs/getting-started/installation/operator/modules/authorizationv2.0.md
content/v1/deployment/csmoperator/modules/authorization v2.0.md
content/v2/deployment/csmoperator/modules/authorization v2.0.md

Remove kvEnginePath from Auth v2 installation parameters.
|https://github.com/dell/csm/issues/1785 |

[bug-1785]: Remove kvEnginePath from Auth v2 parameters

---

content/docs/concepts/authorization/v1.x/_index.md
content/v1/authorization/v1.x/_index.md
content/v1/deployment/rpm/modules/upgrade/authorization.md
content/v2/authorization/v1.x/_index.md
content/v3/authorization/v1.x GA/_index.md

Clarify version decrepancies for Authorization components.
|https://github.com/dell/csm/issues/1796 |

Clarify version discrepancy for Authorization components

---

content/docs/getting-started/installation/helm/modules/observability/_index.md

Documentation updates for Grafana Migration from Angular JS to React
| https://github.com/dell/csm/issues/1755 |

Docs update grafana upgrade

---

content/docs/concepts/authorization/v1.x/release/_index.md
content/docs/concepts/authorization/v2.x/release/_index.md
content/docs/concepts/csidriver/release/powerflex.md
content/docs/concepts/csidriver/release/powermax.md
content/docs/concepts/csidriver/release/powerscale.md
content/docs/concepts/csidriver/release/powerstore.md
content/docs/concepts/observability/release/_index.md
content/docs/concepts/replication/release/_index.md
content/docs/concepts/resiliency/release/_index.md
content/docs/release/csminstallationwizard.md
content/docs/release/csmoperator.md
content/docs/supportmatrix/_index.md
content/v1/authorization/v1.x/release/_index.md
content/v1/authorization/v2.x/release/_index.md
content/v1/csidriver/release/powerflex.md
content/v1/csidriver/release/powermax.md
content/v1/csidriver/release/powerscale.md
content/v1/csidriver/release/powerstore.md
content/v1/deployment/csminstallationwizard/release/_index.md
content/v1/deployment/csmoperator/release/_index.md
content/v1/observability/release/_index.md
content/v1/prerequisites/_index.md
content/v1/replication/release/_index.md
content/v1/resiliency/release/_index.md

Add support for OCP 4.18 and 4.18 virtualization 
| https://github.com/dell/csm/issues/1560|

Add support for OCP 4.18

---

content/docs/authorization/v1.x/release/_index.md
content/docs/authorization/v2.x/release/_index.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/deployment/csminstallationwizard/release/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/observability/release/_index.md
content/docs/prerequisites/_index.md
content/docs/replication/release/_index.md
content/docs/resiliency/release/_index.md

Add support for OCP 4.18 and 4.18 virtualization 
| https://github.com/dell/csm/issues/1560|

Add support for OCP 4.18 - 1.13 branch

---

content/docs/getting-started/installation/kubernetes/powerstore/csmoperator/_index.md
content/docs/getting-started/installation/kubernetes/powerstore/helm/_index.md
content/docs/getting-started/installation/openshift/powerstore/csmoperator/_index.md

Add reference to the HBNFS parameters for PowerStore.
| https://github.com/dell/csm/issues/1742 |

Add PowerStore HBNFS configurable parameters

---

.github/CODEOWNERS
.github/workflows/deploy.yml

Update hugo version to 0.145.0
| |

Update hugo version to 0.145.0

---

.github/workflows/broken-links.yaml
.github/workflows/deploy.yml
content/docs/authorization/v2.x/release/_index.md
content/docs/csidriver/release/powerflex.md
content/docs/csidriver/release/powermax.md
content/docs/csidriver/release/powerscale.md
content/docs/csidriver/release/powerstore.md
content/docs/deployment/csminstallationwizard/release/_index.md
content/docs/deployment/csmoperator/release/_index.md
content/docs/deployment/helm/drivers/upgrade/powerflex.md
content/docs/observability/release/_index.md
content/docs/prerequisites/_index.md
content/docs/replication/release/_index.md
content/docs/resiliency/_index.md
content/docs/resiliency/release/_index.md

Update patch 1.13.1 release note to include fix details
| #https://github.com/dell/csm/issues/1811  |

Update patch 1.13.1 release note to include fix details

---

content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.13.0.template

Update CSM template for installation wizard 
| https://github.com/dell/csm/issues/1791 |
-  [X] Have you run a grammar and spell checks against your submission?

Update CSM template for installation wizard 

---

content/docs/concepts/replication/_index.md
content/docs/concepts/replication/pvc-remap.md

Add pvcremap feature guide. It includes explanation, enable/disable scenario before and after installation of csm-replication module.
| https://github.com/dell/csm/issues/1850 |

Add pvcremap feature guide

---

content/docs/concepts/csidriver/features/powerstore.md
content/docs/getting-started/installation/installationwizard/src/csm-versions/default-values.properties
content/docs/getting-started/installation/installationwizard/src/index.html
content/docs/getting-started/installation/installationwizard/src/static/js/generate-yaml.js
content/docs/getting-started/installation/installationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/getting-started/installation/installationwizard/src/static/js/tests/utility.test.js
content/docs/getting-started/installation/installationwizard/src/static/js/ui-functions.js
content/docs/getting-started/installation/installationwizard/src/static/js/utility.js
content/docs/getting-started/installation/installationwizard/src/templates/helm/csm-1.14.0-values.template
content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-powerstore-1.14.0.template
content/docs/getting-started/installation/kubernetes/powerstore/csmoperator/_index.md
content/docs/getting-started/installation/kubernetes/powerstore/helm/_index.md
content/docs/getting-started/installation/openshift/powerstore/csmoperator/_index.md

Documentation changes for multi NAS Support
| https://github.com/dell/csm/issues/1758 |

Documentation changes for multi NAS Support

---

content/docs/concepts/csidriver/features/powerflex.md
content/docs/getting-started/installation/kubernetes/powerflex/helm/_index.md
content/docs/getting-started/installation/openshift/powerflex/csmoperator/_index.md

Documentation for PowerFlex Driver to expose SFTP settings 
|https://github.com/dell/csm/issues/1752 |

Documentation for PowerFlex Driver to expose SFTP settings 

---

content/docs/concepts/csidriver/features/powerstore.md
content/docs/getting-started/installation/kubernetes/powerstore/csmoperator/_index.md
content/docs/getting-started/installation/kubernetes/powerstore/helm/_index.md
content/v1/csidriver/features/powerstore.md
content/v1/deployment/csmoperator/drivers/powerstore.md
content/v1/deployment/helm/drivers/installation/powerstore.md
content/v2/csidriver/features/powerstore.md
content/v2/deployment/csmoperator/drivers/powerstore.md
content/v2/deployment/helm/drivers/installation/powerstore.md

This PR adds a note for skipCertificateValidation flag of PowerStore driver.
|dell/csm#1881|

Add note for flag of PowerStore driver.

---

content/docs/getting-started/installation/installationwizard/src/index.html
content/docs/getting-started/installation/installationwizard/src/static/js/generate-yaml.js
content/docs/getting-started/installation/installationwizard/src/static/js/tests/generate-yaml.test.js
content/docs/getting-started/installation/installationwizard/src/static/js/ui-functions.js
content/docs/getting-started/installation/installationwizard/src/templates/helm/csm-1.14.0-values.template

Installation wizard changes for exposing SFTP settings
| https://github.com/dell/csm/issues/1752 |

Installation wizard changes for exposing SFTP setting

---

content/docs/supportmatrix/_index.md

Updating the csm-docs with new versions supported on CSM 1.14.
Support Matrix:
PowerScale: 9.11
Unity: 5.5
|https://github.com/dell/csm/issues/1707, https://github.com/dell/csm/issues/1750 |

Version update pertaining to CSM 1.14.

---

content/docs/concepts/csidriver/features/powerflex.md
content/docs/concepts/csidriver/features/powermax.md
content/docs/concepts/csidriver/features/powerstore.md
content/docs/concepts/csidriver/features/unity.md
content/v1/csidriver/features/powerflex.md
content/v1/csidriver/features/powermax.md
content/v1/csidriver/features/powerstore.md
content/v1/csidriver/features/unity.md
content/v2/csidriver/features/powerflex.md
content/v2/csidriver/features/powermax.md
content/v2/csidriver/features/powerstore.md
content/v2/csidriver/features/unity.md

Node Label Documentation Changes
| https://github.com/dell/csm/issues/1808 |

 Node Label Documentation Changes

---

.github/workflows/deploy.yml

Update the deploy.yaml to CSM 1.14
To update the deploy.yaml to CSM 1.14
|https://github.com/dell/csm/issues/1707 |

Update deploy.yml to 1.14.0

---

content/docs/concepts/csidriver/troubleshooting/powerflex.md
content/docs/release/_index.md

Reverts the PR dell/csm-docs#1560 as this change was intended to be merged into the release branch, but was mistakenly merged into main.

Revert "Powerflex Minimal Manifest Documentation Update"

---

content/docs/support/qualified.md
content/v1/support/cert-csi/qualified.md

This PR updates the Community Qualified Configurations Page  for Main Branch
| https://github.com/dell/csm/issues/1764|

Updated Community Qualified Configurations

---

content/docs/concepts/csidriver/_index.md

Link to raw block official doc changed, now fixed
Reindent table so it is cleaner
| https://github.com/dell/csm/issues/1896 |

Fix broken link & realign tables

---

content/docs/getting-started/installation/installationwizard/src/templates/helm/csm-1.13.0-values.template
content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-isilon-1.13.0.template
content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-powermax-1.13.0.template
content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-powerstore-1.13.0.template
content/docs/tooling/cli/_index.md
content/v1/getting-started/installation/installationwizard/src/templates/helm/csm-1.13.0-values.template
content/v1/getting-started/installation/installationwizard/src/templates/operator/csm-isilon-1.13.0.template
content/v1/getting-started/installation/installationwizard/src/templates/operator/csm-powermax-1.13.0.template
content/v1/getting-started/installation/installationwizard/src/templates/operator/csm-powerstore-1.13.0.template
content/v1/tooling/cli/_index.md
content/v2/deployment/csminstallationwizard/src/templates/helm/csm-1.13.0-values.template
content/v2/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.13.0.template
content/v2/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.13.0.template
content/v2/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.13.0.template
content/v2/deployment/csmoperator/_index.md
content/v2/support/cli/_index.md

Incorrect side car versions in Installation wizard 
| https://github.com/dell/csm/issues/1908 |

Incorrect side car versions in Installation wizard 

---

content/docs/concepts/csidriver/features/powerflex.md
content/v1/concepts/csidriver/features/powerflex.md

Updated the sftp secrets (`sftp-secret-private` and `sftp-secret-public`) from .yaml to .crt files for better clarify.
| https://github.com/dell/csm/issues/1931 |

Updated the SFTP secrets to .crt files

---

content/docs/supportmatrix/_index.md

This PR fixes a broken referencelink for the supported Orchestration Platform on the Support Matrix page in the CSM Docs.
| dell/csm#1938|

[BUG]: Broken referencelink on Support Matrix

---

content/docs/concepts/csidriver/features/powerflex.md
content/docs/concepts/csidriver/features/powermax.md
content/docs/concepts/csidriver/features/powerstore.md
content/docs/concepts/csidriver/features/unity.md

Update Note for NFS Labels for PowerFlex, PowerStore, PowerMax and Unity Driver.
| dell/csm#1808|

Update Note for NFS Labels

---

content/docs/concepts/authorization/v2.x/configuration/_index.md
content/docs/getting-started/installation/helm/modules/authorizationv2-0.md
content/docs/getting-started/installation/kubernetes/powerflex/helm/_index.md
content/docs/getting-started/installation/operator/modules/authorizationv2-0.md
content/v2/deployment/csminstallationwizard/src/index.html
content/v3/deployment/csminstallationwizard/src/index.html

Add documentation for configuring storage system credentials with a Secret Provider Class or kubernetes secret.
|https://github.com/dell/csm/issues/1468 |

Enhance Authorization deployments with K8s Secret Provider

---

content/docs/concepts/authorization/v2.x/configuration/_index.md
content/docs/getting-started/installation/helm/modules/authorizationv2-0.md
content/docs/getting-started/installation/operator/modules/authorizationv2-0.md

- Describe Conjur SecretProviderClass
- Provide configuration example for Conjur
|https://github.com/dell/csm/issues/1468 |

[feature-1468]: CSM Authorization Helm - Conjur Integration

---

assets/scss/_content.scss
content/docs/getting-started/installation/operator/modules/authorizationv2-0.md
layouts/shortcodes/tabpane.html

- Fixed spacing and code block color in tab body 
|https://github.com/dell/csm/issues/1896|

Fix tab pane color

---

content/docs/getting-started/installation/helm/modules/authorizationv2-0.md
content/docs/getting-started/installation/operator/modules/authorizationv2-0.md
content/docs/getting-started/upgrade/helm/module/authorization.md
content/docs/getting-started/upgrade/operator/authorization_upgrade.md

PR to add to upgrade steps for authorization v2.2.0 -> v2.3.0
|https://github.com/dell/csm/issues/1468 |

Update upgrade steps for Authorization

---

content/docs/getting-started/installation/helm/modules/authorizationv2-0.md
content/docs/getting-started/installation/kubernetes/powerflex/helm/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/kubernetes/powermax/helm/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/kubernetes/powerscale/helm/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/kubernetes/powerstore/helm/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/openshift/powerflex/csmoperator/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/openshift/powermax/csmoperator/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/openshift/powerscale/csmoperator/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/openshift/powerstore/csmoperator/csm-modules/authorizationv2-0.md
content/docs/getting-started/installation/operator/modules/authorizationv2-0.md

Fixed link to powerstore authorization installation configuration
| https://github.com/dell/csm/issues/1947 |

Powerstore authorization installation link fix

---

content/docs/concepts/csidriver/features/powerscale.md

Add note to relevant Powerscale feature saying CSM Modules are not supported (not tested).
|https://github.com/dell/csm/issues/1896 |

CSM Modules not supported for Powerscale multi-tenant access zones

---

content/docs/concepts/replication/disaster-recovery.md

Document steps to provide more clarity during PowerScale unplanned failover
https://github.com/dell/csm/issues/1896

Document steps to provide more clarity during PowerScale unplanned failover

---

content/docs/concepts/authorization/v2.x/configuration/powerstore/_index.md

Fix the PowerStore secret example in docs
| https://github.com/dell/csm/issues/1947 |

Corrected PowerStore Secret section for Authorization

---

content/_index.html
content/docs/release/_index.md
content/docs/support/_index.md
content/docs/support/contributionguidelines/_index.md
content/docs/supportmatrix/_index.md
content/docs/tooling/cert-csi/_index.md
content/v1/support/_index.md
content/v1/support/contributionguidelines/_index.md
content/v1/tooling/cert-csi/_index.md
content/v2/support/_index.md
content/v2/support/cert-csi/_index.md
content/v2/support/contributionguidelines/_index.md
content/v3/support/_index.md
content/v3/support/cert-csi/_index.md
content/v3/support/contributionguidelines/_index.md
layouts/docs/content.html
layouts/docs/list.html
layouts/partials/feedback1.html
layouts/shortcodes/message.html
layouts/v1/list.html
layouts/v1/single.html
layouts/v2/list.html
layouts/v2/single.html
layouts/v3/list.html
layouts/v3/single.html

Duplicate of PR #1666.
| https://github.com/dell/csm/issues/1896|

Update the community changes and broken links

---

content/docs/supportmatrix/component-version.md

Updated the compatibility matrix with the image versions.
| E960 |

Add sha256 sums for images
