- content/docs/deployment/_index.md
- content/docs/deployment/csmcli.md
- Adds note about the CSM Installer only supporting environments without existing CSM or CSI drivers.
- Adds details about optional meta-data field when creating storage systems
> Updated docs for common installer

- .github/workflows/deploy.yml
- .github/workflows/deploy1.yml
- layouts/partials/page-meta-links.html
As part of removing forbidden words, we have changed our default branch.
This PR fixes the places where it was referring to the prior name.
> Aligning with branching strategy

- content/docs/contributionguidelines/_index.md
- content/docs/csidriver/installation/operator/_index.md
- content/docs/csidriver/installation/operator/powerflex.md
There is a warning to not mess with sidecar values in the [general operator documentation for all drivers](https://dell.github.io/csm-docs/docs/csidriver/installation/operator/#sidecars), but, in PowerFlex, we need the customer add some values to the yaml file (MDM IPs, etc.), and this is not made clear in the [PowerFlex documentation](general operator documentation for all drivers), causing confusion for users. This is resolved in this PR, with clarifications to both the general operator docs and to the PowerFLex operator docs.
| |
> Fix operator install docs

- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/installation/helm/powerflex.md
- content/docs/csidriver/installation/helm/powermax.md
- content/docs/csidriver/installation/helm/powerstore.md
- content/docs/csidriver/installation/helm/unity.md
- content/docs/csidriver/upgradation/drivers/isilon.md
- content/docs/csidriver/upgradation/drivers/powerflex.md
- content/docs/csidriver/upgradation/drivers/powermax.md
- content/docs/csidriver/upgradation/drivers/powerstore.md
- content/docs/csidriver/upgradation/drivers/unity.md
As part of true open source model, CSI driver documentation will now enable to fetch v2.0.0 of the drivers directly during clone
| Issue 93 |
> Update documentation to enable users to clone v2.0.0 of drivers directly

- content/docs/csidriver/troubleshooting/powerflex.md
The root cause of the error I was seeing that caused me to add a troubleshooting tip was actually that I was using an old image, so I'm removing the tip as it is inaccurate.
| |
> Remove incorrect troubleshooting tip

- content/docs/csidriver/_index.md
Added support for google anthos, volume health monitoring and OneFS 9.3
|https://github.com/dell/csm/issues/123 |
> Added volume health monitor in CSI spec support

- content/docs/csidriver/_index.md
RWOP - Wrong support for PowerMax in Matrix 
| https://github.com/dell/csm/issues/129 |
> RWOP - Wrong support for PowerMax in Matrix 

- content/docs/csidriver/_index.md
- content/docs/csidriver/features/powerflex.md
- content/docs/csidriver/installation/helm/powerflex.md
- content/docs/csidriver/release/powerflex.md
This PR removes all mention/claim of Fedora CoreOS support for PowerFlex driver. 
This is needed because FCOS was deprioritized for SDC team, resulting in PowerFlex driver 2.1 being unable to install on FCOS clusters
| https://github.com/dell/csm/issues/131|
> Remove fedora

- content/docs/csidriver/release/powerflex.md
- content/docs/observability/deployment/online.md
- content/docs/observability/upgrade/_index.md
This PR updates CSM for Observability upgrade documentation to support installer scripts. 
|https://github.com/dell/csm/issues/151 |
> Observability upgrade for installer scripts

- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/release/powerscale.md
- content/docs/csidriver/upgradation/drivers/isilon.md
Updated version to 2.2 for CSI powerscale and added list of new features.
https://github.com/dell/csm/issues/195
> CSI-Powerscale v2.2.0 version update changes

- content/docs/replication/deployment/configmap-secrets.md
- content/docs/replication/deployment/installation.md
Adds missing parts about hostAlises feature for replication that allows users to inject FQDN:IP entries into their controller's pods
> replication hostAliases documented

- content/docs/csidriver/features/powerstore.md
- content/docs/csidriver/installation/helm/powerstore.md
Documentation update for POSIX and NFSv4 ACLs support
|dell/csm#191 |
> Documentation update for POSIX and NFSv4 ACLs support

- content/docs/csidriver/installation/helm/unity.md
Update installation example - Installation helm page of unity XT with supported K8s 
| https://github.com/dell/csm/issues/128 |
> Update installation example - Installation helm page of unity XT with supported K8s 

- content/docs/csidriver/installation/helm/powerstore.md
Updated documentation for FSGroup policy
| https://github.com/dell/csm/issues/167 |
> FSGroup doc update

- content/docs/csidriver/installation/operator/_index.md
- content/docs/csidriver/release/operator.md
- content/docs/csidriver/upgradation/drivers/operator.md
Operator docs changes to update versions reference.
| https://github.com/dell/csm/issues/195|
> Operator docs changes to update version references

- content/docs/csidriver/features/powerstore.md
- content/docs/csidriver/installation/helm/powerstore.md
Reverting POSIX and NFSv4 ACL documentation updates in main branch
| dell/csm#191|
> Reverting POSIX and NFSv4 ACLs doc updates

- content/docs/csidriver/features/unity.md
- content/docs/csidriver/installation/helm/unity.md
- content/docs/csidriver/installation/operator/_index.md
- content/docs/csidriver/installation/operator/unity.md
- content/docs/csidriver/upgradation/drivers/unity.md
Unity docs changes to update versions reference.
| https://github.com/dell/csm/issues/195 |
> Unity docs changes to update versions reference.

- content/docs/csidriver/features/powerstore.md
- content/docs/csidriver/installation/helm/powerstore.md
- content/docs/csidriver/installation/operator/powerstore.md
Documentation updates for POSIX and NFSv4 ACL support in CSI PowerStore
|dell/csm#191 |
> POSIX and NFSv4 ACL support in CSI PowerStore

- content/docs/resiliency/troubleshooting.md
Adding the resiliency design limitation of zombie resources to the troubleshooting guide as it covers a workaround
| https://github.com/dell/csm/issues/219|
> Add design limitiation to troubleshooting section

- content/docs/observability/deployment/_index.md
This PR fixes a formatting issue in prometheus-values.yaml as well as the Prometheus data source url for Grafana. It also revises the supported version for Prometheus to match the tag version in prometheus-values.yaml.
|https://github.com/dell/csm/issues/259 
https://github.com/dell/csm/issues/278|
> Fix Observability Post Installation Dependency Issues

- content/docs/csidriver/release/powermax.md
- content/docs/replication/_index.md
Added support to Kubernetes 1.24 for Powermax. 
| https://github.com/dell/csm/issues/298 |
> Adding k8 1.24 support for PowerMax

- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/installation/operator/_index.md
- content/docs/csidriver/release/powerscale.md
- content/docs/resiliency/_index.md
- content/docs/resiliency/deployment.md
Update features for csi-powerscale 2.3.
Update resiliency support for csi-powerscale.
Update side cars and k8s 1.24 .
https://github.com/dell/csm/issues/298
https://github.com/dell/csm/issues/263
https://github.com/dell/csm/issues/262
https://github.com/dell/csm/issues/262
> CSI-PowerScale driver & resiliency update

- content/docs/authorization/cli.md
- Adds missing `karavictl rolebinding delete` CLI for Authorization
- Removes duplicate `karavictl tenant get` from table
- Fixed samples for `karavictl tenant get` to use the `--name` parameter.
| https://github.com/dell/csm/issues/314  |
> Updated Authorization CLI and added missing rolebinding delete

- content/docs/authorization/troubleshooting.md
- Adds troubleshooting distinctions between the Authorization RPM and Helm deployments.
- Adds troubleshooting for the `request denied for path` error for CSI PowerFlex v2.3.0.
|https://github.com/dell/csm/issues/353 |
> Authorization: add troubleshooting for request path denied

- content/docs/authorization/deployment/rpm/_index.md
Updates the prerequisites for the Authorization RPM deployment to install container-selinux and a specific version of k3s-selinux.
|https://github.com/dell/csm/issues/393 |
> Bug 393 authorization selinux

- content/docs/authorization/deployment/helm/_index.md
- content/docs/authorization/deployment/rpm/_index.md
Add alternative method to extract the token and convert to YAML format. Added note in both Helm and RPM deployment sections. There are more than one way to do this but felt that sed is in all major distributions and not everyone may use Python's json module which is another option I thought about.
- Compared output of original command and new alternative. The output is the same except for a newline at the top and bottom with the new approach. Not an issue as YAML is tolerant of blank lines. Did not want to add complexity to the sed command.
- Imported secret into Kubernetes without error.
| https://github.com/dell/csm/issues/390|
- [n/a] Have you added high-resolution images?
> Use sed as alternative to jq

- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/release/powerscale.md
- content/docs/csidriver/upgradation/drivers/isilon.md
- content/docs/resiliency/_index.md
2.4 driver version related changes.
Add feature implemented in 2.4 driver.
https://github.com/dell/csm/issues/362
https://github.com/dell/csm/issues/350
> csi powerscale 2.4 related updates

- content/docs/cli/_index.md
Now dellctl supports cluster registration with optional uids. This PR is to reflect the same changes in documentation.
| dell/csm#350|
> dellctl- support cluster registration with uids

- content/docs/authorization/cli.md
- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/installation/helm/powerflex.md
- content/docs/resiliency/deployment.md
This PR updates CSM Authorization documentation to include --array-insecure flag when creating or updating storage systems. PR also addresses improvements to add links to Resiliency deployment page from podmon sidecar references in values.yaml for applicable drivers.
|https://github.com/dell/csm/issues/416|
> Update CSM Authorization documentation to include --array-insecure flag

- content/docs/_index.md
- content/docs/application-mobility/_index.md
- content/docs/application-mobility/deployment.md
- content/docs/application-mobility/troubleshooting.md
- content/docs/application-mobility/uninstallation.md
- content/docs/application-mobility/use_cases.md
Application Mobility Documentation
|  https://github.com/dell/csm/issues/350 |
> Application Mobility Documentation

- content/docs/csidriver/installation/helm/powermax.md
- content/docs/csidriver/release/powermax.md
Updated PowerPath support for PowerMax
| https://github.com/dell/csm/issues/436 |
> update powerpath support for Powermax

- content/docs/csidriver/features/powerflex.md
It was identified that documentation for creating static provisioning on PowerFlex was missing. Similar to other drivers that support this feature, a section for the documentation was added for consistency. 
> Add static provisioning example to PowerFlex

- content/docs/authorization/Backup and Restore/_index.md
- content/docs/authorization/Backup and Restore/helm/_index.md
- content/docs/authorization/Backup and Restore/rpm/_index.md
Adds documentation for backing up and restoring Authorization data.
|https://github.com/dell/csm/issues/410 |
> [bug-410]: Authorization backup and restore

- content/docs/observability/_index.md
- content/docs/observability/deployment/_index.md
- content/docs/observability/deployment/helm.md
- content/docs/observability/deployment/offline.md
- content/docs/observability/deployment/online.md
- content/docs/observability/design/_index.md
- content/docs/observability/metrics/powerscale.md
- content/docs/observability/release/_index.md
- content/docs/observability/troubleshooting/_index.md
- content/docs/observability/upgrade/_index.md
Add CSM observability for PowerScale to csm-docs, and update docs for online/offline install and upgrade.
| https://github.com/dell/csm/issues/379|
> PowerScale Obs doc update for CSM Observability 1.3.0

- content/docs/_index.md
- content/docs/deployment/_index.md
- content/docs/release/_index.md
- content/docs/secure/encryption/release.md
- content/docs/troubleshooting/_index.md
Added references to Encryption from the common pages.
| |
> Encryption common

- content/docs/applicationmobility/use_cases.md
Add documentation about using CRDs instead of dellctl for Application Mobility
> Add documentation about using CRDs instead of dellctl for Application Mobility

- content/docs/csidriver/upgradation/drivers/powerstore.md
Update 5th and 6th point in CSI-Powerstore helm upgrade procedure 
|https://github.com/dell/csm/issues/484|
> CSI-Powerstore: Update helm upgrade procedure

- content/docs/resiliency/deployment.md
Ignore volumeless pods with Resiliency label.
| #https://github.com/dell/csm/issues/493 |
> Ignore volumeless pods with Resiliency label

- content/docs/csidriver/_index.md
- Added 1.25 Kubernetes version.
- Removed 1.22 Kubernetes version.
- Added (3.2) array version.
|https://github.com/dell/csm/issues/478
https://github.com/dell/csm/issues/482 |
Test:
> CSI-Powerstore: Add 1.25 k8s version and 3.2 array support in support matrix 

- content/docs/csidriver/_index.md
- content/docs/csidriver/installation/operator/_index.md
- content/docs/csidriver/release/powerstore.md
- Add OpenShift 4.11 Support in the Support Matrix.
- Add Operator support for 2.5 driver.
- Update Release Notes
|https://github.com/dell/csm/issues/478 |
|https://github.com/dell/csm/issues/480 |
|https://github.com/dell/csm/issues/482|
|https://github.com/dell/csm/issues/483 |
Test:
> CSI-Powerstore Add Operator support for 2.5 Driver and Update release notes

- content/docs/snapshots/volume-group-snapshots/_index.md
- content/v1/snapshots/volume-group-snapshots/_index.md
The documentation for the volume-group-snapshot common docs doesn't have the install method in it :
https://dell.github.io/csm-docs/docs/snapshots/volume-group-snapshots/
We have to jump on the github page to know about the install method or upgrade. Hence, It will be better to have it centralized in the doc portal like any other CSM module.
Also updated v1 docs just to be sure.
| |
> update vgs docs

- content/docs/references/cli/_index.md
Add new dellctl commands to create and manage schedules for backups.
|dell/csm#491 |
> dellctl schedule commands

- content/docs/deployment/_index.md
- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/drivers/powerflex.md
Adding support for PowerFlex in csm-operator docs, removing tech preview since we are going v1.
@mbasha-dell @kumarkgosa @abhi16394 if one of you could take a look at the SDC deployment section, I would really appreciate that, I'm not as knowledgeable in that area.
| https://github.com/dell/csm/issues/477 |
> Csm operator pflex support and v1

- content/docs/applicationmobility/_index.md
- content/docs/secure/encryption/_index.md
Update app mobility secure support for OpenShift 4.11 and Kubernetes 1.25.
| dell/csm#478 |
| dell/csm#480 |
> Updated support for Application Mobility and Encryption

- content/docs/applicationmobility/deployment.md
Added entry for restic privileged mode used by the helm chart.
| https://github.com/dell/csm/issues/480|
> Added entry for restic privileged mode

- content/docs/csidriver/features/powerflex.md
The changes in this PR includes fixing the indentation issues for the feature QoS settings for CSI-PowerFlex driver.
| https://github.com/dell/csm/issues/533 |
> PowerFlex QoS settings docs fix

- content/docs/csidriver/installation/helm/isilon.md
Modification in Volume health monitor config parameter.
The variable mention i.e. `interval` is correct for csi-powerscale, but the comment is not.
|[203](https://github.com/dell/csm/issues/203) |
> Update healthMonitorInterval to interval in comment

- content/docs/csidriver/_index.md
- Removed MKE 3.5.x version
- Updated MKE version to 3.6.0
| dell/csm#583
> Powerflex documentation update: Added support for MKE 3.6.0

- content/docs/references/cli/_index.md
dellctl images is a new cmd which is introduced in the 1.5.1 release. This cmd helps us in listing the Container images needed by csi driver. 
| https://github.com/dell/csm/issues/582 |
> added the documentation for dellctl images command.

- content/docs/authorization/configuration/powerflex/_index.md
This PR adds a new bullet point in CSM Authorization Poweflex configuration page to include dellctl.
| https://github.com/dell/csm/issues/408|
> Feature 408: update CSM authorization documentation to include dellctl

- content/docs/csidriver/upgradation/drivers/powerstore.md
Updated file name from `helm/config.yaml` to `samples/secret/secret.yaml `
| https://github.com/dell/csm/issues/643|
> CSI PowerStore : Update file name from config.yaml to secret.yaml

- content/docs/csidriver/features/powerflex.md
- content/docs/csidriver/installation/helm/powerflex.md
Documentation update for CSI PowerFlex driver includes:
- Updates for rename SDC feature.
- Updates for Pre-approving SDC by GUID feature.
| https://github.com/dell/csm/issues/402 |
> CSI PowerFlex driver docs update - renameSDC and preapprovedGUID

- content/docs/_index.md
Updated Powerstore driver version to 2.5.1 for CSM 1.5.1
| https://github.com/dell/csm/issues/582 |
> Updated Powerstore driver version to 2.5.1 for CSM 1.5.1

- content/docs/deployment/_index.md
- content/docs/deployment/csmoperator/drivers/_index.md
- content/docs/deployment/csmoperator/drivers/powerstore.md
- content/docs/deployment/csmoperator/release/_index.md
Added documentation for Powerstore install for CSM Operator
| https://github.com/dell/csm/issues/613 |
> Documentation for Powerstore Install support in csm operator

- content/docs/authorization/deployment/rpm/_index.md
- content/docs/authorization/release/_index.md
- content/docs/authorization/upgrade.md
Upgraded CSM Authorization installation/upgrade documentation. 
| https://github.com/dell/csm/issues/642 |
| |
> Update csm auth upgrade procedure

- content/docs/authorization/cli.md
- content/docs/authorization/configuration/proxy-server/_index.md
Doc updates - CSM Authorization for Powerflex Pre-approved GUIDs
| https://github.com/dell/csm/issues/402 |
> Added csm auth docs for Preapproved guid feature

- content/docs/references/FAQ/_index.md
Fixed the Broken Links raised in the Issue (https://github.com/dell/csm/issues/715)
|https://github.com/dell/csm/issues/715|
> Fixing the Broken Links in FAQ Section

- content/docs/csidriver/release/powerstore.md
- content/docs/csidriver/upgradation/drivers/powerstore.md
Update release notes & upgrade steps for CSI-PowerStore
> Update CSI-PowerStore release notes & upgrade steps

- content/docs/authorization/cli.md
- content/docs/authorization/configuration/proxy-server/_index.md
- content/docs/authorization/deployment/helm/_index.md
- content/docs/authorization/deployment/rpm/_index.md
- content/docs/authorization/troubleshooting.md
- content/docs/deployment/csmoperator/modules/authorization.md
Updates to remove the tenant-service endpoint and for `karavictl` tenant commands to send requests to the proxy-server.
| https://github.com/dell/csm/issues/725|
> [feature-725]: Remove tenant service ingress

- content/docs/_index.md
- content/docs/csidriver/_index.md
- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/release/powerscale.md
- content/docs/csidriver/upgradation/drivers/isilon.md
- Updated CSI PowerScale version from 2.6.0 to 2.6.1 and CSM version from 1.6.0 to 1.6.1
- Added Fixed issue (replication) to PowerScale driver.
- Changes from PR https://github.com/dell/csm-docs/pull/569 will eventually move over here after 1.6.1 branch is rebased from main.
| https://github.com/dell/csm/issues/753 |
> Added changes for 1.6.1 release

- content/docs/authorization/cli.md
- content/docs/authorization/configuration/proxy-server/_index.md
- content/docs/authorization/deployment/helm/_index.md
- content/docs/deployment/csmoperator/modules/authorization.md
Updated documentation on the Karavictl, and Authorization pages to cover the changes made by this PR: (https://github.com/dell/karavi-authorization/pull/226) which covers role-service being removed from the Ingress.
|https://github.com/dell/csm/issues/725|
> Removing ingress for role-service

- content/docs/csidriver/installation/helm/isilon.md
|https://github.com/dell/csm/issues/762 |
- [] Have you added high-resolution images?
> Multi array support documentation improvements

- content/docs/references/cli/_index.md
- content/v1/references/cli/_index.md
This pr adds the Powerflex changes for the k8s registry migration from old(k8s.gcr.io) to new( registry.k8s.io)
| https://github.com/dell/csm/issues/744  |
> powerflex changes for k8s registry migration from old to new( registry.k8s.io)

- config.toml
Updating Docs version from 1.6 to 1.6.1 for the release 1.6.1 branch https://github.com/dell/csm-docs/pull/580
> Update 1.6 to 1.6.1

- content/docs/authorization/cli.md
- content/docs/authorization/configuration/proxy-server/_index.md
`karavictl generate token` updates for outputting yaml that can be applied in k8s without post-processing.
|https://github.com/dell/csm/issues/767 |
> [bug-767]: karavictl generate token outputs yaml

- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/modules/resiliency.md
- content/docs/deployment/csmoperator/release/_index.md
Adding support of resiliency module for supported drivers by CSM-Operator.
|https://github.com/dell/csm/issues/739|
|https://github.com/dell/csm/issues/785|
> Resiliency module support by CSM-Operator

- content/docs/csidriver/installation/operator/isilon.md
- content/docs/deployment/csmoperator/drivers/powerscale.md
The instructions in the CSM Operator deployment for PowerScale is inconsistent in the use of the namespace name. In some places test-isilon is used but in some of the example code the namespace isilon is used.
|[793](https://github.com/dell/csm/issues/793) |
> Fix inconsistency in isilon namespace

- .github/CODEOWNERS
- content/docs/csidriver/_index.md
- content/docs/csidriver/features/powerscale.md
- content/docs/csidriver/installation/helm/isilon.md
Added the documentation for supporting the Storage Capacity Tracking feature in CSI-PowerScale.
|https://github.com/dell/csm/issues/743 |
> Added docs for Storage Capacity Tracking support in PowerScale

- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/modules/replication.md
- content/docs/replication/deployment/install-repctl.md
- content/docs/replication/deployment/installation.md
Cleared up confusing documentation for installing Replication via CSM Operator. The current documentation is referring to the Helm repctl section for installation steps and these steps are not compatible with the Operator install process. This change also requires fixes in Operator to handle the stretched cluster case. I will update with the PRs for those changes one I get them.
| [788](https://github.com/dell/csm/issues/788)|
> Fixes for Operator install of Replication

- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/installation/helm/powerflex.md
- content/docs/csidriver/installation/helm/powermax.md
- content/docs/csidriver/installation/helm/powerstore.md
- content/docs/csidriver/installation/helm/unity.md
- content/docs/csidriver/installation/operator/_index.md
Added a copy button on syntax code blocks with prism in some pages. Modified the code-blocks as required.
> Updating-Copy-Buttons

- content/docs/csidriver/installation/offline/_index.md
- content/docs/csidriver/release/operator.md
- content/docs/csidriver/upgradation/drivers/operator.md
Update csi operator 1.12.0 release notes.
| https://github.com/dell/csm/issues/743|
> Update csi operator 1.12.0 release notes

- content/docs/csidriver/features/powerscale.md
- content/v1/csidriver/features/powerscale.md
- content/v2/csidriver/features/powerscale.md
- content/v3/csidriver/features/powerscale.md
Updated the documentation for CSI Ephemeral Volumes in powerscale.
> Updated the documentation for CSI Ephemeral Volumes in powerscale.

- content/docs/csidriver/installation/helm/powerstore.md
- content/docs/csidriver/upgradation/drivers/powerstore.md
Document changes using centralized helm for driver installation
| https://github.com/dell/csm/issues/877|
> Powerstore-Centralized-helm-Changes

- content/docs/csidriver/features/powerstore.md
Added Prefix "csi.dell.com/" for all the [configurable volume attributes for block volume](https://dell.github.io/csm-docs/docs/csidriver/features/powerstore/#configurable-volume-attributes-optional:~:text=PowerStore%20CSI%20driver%3A-,Block%20Volume,-NFS%20Volume)
Added Prefix "csi.dell.com/" for all the [configurable volume attributes for the file system](https://dell.github.io/csm-docs/docs/csidriver/features/powerstore/#configurable-volume-attributes-optional:~:text=Block%20Volume-,NFS%20Volume,-description%0Aappliance_id%0Avolume_group_id)
| https://github.com/dell/csm/issues/879|
> Configurable Volume Attributes 

- content/docs/authorization/cli.md
- Removes `config` flag which isn't used
- Updates examples with `addr` flag
- Updates to say that `admin-token` and `addr` flag are required for relevant commands
| https://github.com/dell/csm/issues/895|
> [bug-985]: Update karavictl CLI 

- content/docs/authorization/cli.md
Fixes minor issues in https://github.com/dell/csm-docs/pull/716.
- storage create/update array-insecure flag should be optional
- tenant create/update approvesdc flag should be optional
- remove "github-auth-provider" from cluster-info example
| https://github.com/dell/csm/issues/895|
> [bug-985]: Update karavictl CLI

- content/docs/replication/deployment/configmap-secrets.md
- content/docs/replication/upgrade.md
- content/v1/replication/deployment/configmap-secrets.md
- content/v2/replication/deployment/configmap-secrets.md
- content/v3/replication/deployment/configmap-secrets.md
- Replication upgrade doc changes for PR https://github.com/dell/csm-replication/pull/104
- Corrected a script file name.
> Replication doc updates for removing init container usage

- content/docs/deployment/csmoperator/modules/observability.md
This PR adds documentation to back [this PR](https://github.com/dell/csm-operator/pull/310) that automates the install of cert-manager with observability when using csm-operator.
| |
> Automate cert-manager install with observability

- content/docs/csidriver/installation/helm/powerflex.md
- content/docs/csidriver/upgradation/drivers/powerflex.md
Document changes using centralized helm for driver installation
| https://github.com/dell/csm/issues/877
> PowerFlex-Centralized-helm-Changes 

- content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
- content/docs/deployment/csminstallationwizard/src/index.html
- content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/static/js/utility.js
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.8.0.template
This PR is to update and fix the defect raised for resiliency module in PowerStore driver operator support.
| (https://github.com/dell/csm/issues/885) |
> Updated the resiliency module for Powerstore operator support in Installation Wizard UI

- content/docs/observability/_index.md
- content/docs/replication/_index.md
Updated Replication & Observability doc to add support for PowerScale OneFS 9.5.
Qual succeeded against the latest 9.5.0.4 version.
> PowerScale OneFS 9.5 qualification for Replication/Observability

- content/docs/deployment/csmoperator/_index.md
PR to include volume snapshot CRDs as an initial step to running the installation script.
|https://github.com/dell/csm/issues/944 |
> Add volume snapshot CRDs to Operator install

- content/docs/csidriver/_index.md
- content/docs/csidriver/features/unity.md
- content/docs/csidriver/installation/helm/unity.md
- content/docs/csidriver/installation/operator/unity.md
- content/docs/csidriver/release/unity.md
- content/docs/deployment/csmoperator/drivers/unity.md
- content/docs/deployment/csmoperator/release/_index.md
Documentation related to SCT changes
| https://github.com/dell/csm/issues/876|
> Added docs for SCT feature Unity XT

- content/docs/csidriver/installation/test/certcsi.md
- content/v1/csidriver/installation/test/certcsi.md
Added example of ephemeral suite since for performance test --attr arg's value type have been modified to keep it consistent with the functional suite. Changed the vol health metrics suite from functional-test to test since it was a typo.
|https://github.com/dell/csm/issues/930|
> Added example of few suites

- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/release/_index.md
This PR
1. Adds support for offline bundle install in csm-operator
2. Updates the Release Notes of csm-operator
3. Updates the support matrix of csm-operator
| https://github.com/dell/csm/issues/939 |
> Add offline bundle support in csm-operator

- content/docs/csidriver/installation/helm/unity.md
Helm changes unity v2.8.0 driver
> Helm changes unity v2.8.0 driver

- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.8.0.template
Updating powermax templates to update correct values . 
|https://github.com/dell/csm/issues/885|
> Updating powermax templates

- content/docs/csidriver/installation/helm/unity.md
`isDefault` should be included in every sample secret for csi-unity since it is a required field.
> [feature-885]: Include isDefault field for every array for csi-unity

- content/docs/csidriver/features/powerscale.md
- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/upgradation/drivers/isilon.md
Document changes for powerscale using a centralized helm for driver installation
and Operator upgrade changes 
|https://github.com/dell/csm/issues/877 |
> Helm changes and Operator upgrade changes

- content/docs/csidriver/installation/helm/unity.md
Unity installation changes for central helm
> Unity installation changes for central helm

- content/docs/deployment/csminstallationwizard/_index.md
- content/docs/deployment/csminstallationwizard/src/index.html
- content/docs/deployment/csminstallationwizard/src/static/js/commands.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/static/js/utility.js
CSM Installation Wizard: Disable Operator option for Powerflex and Unity XT drivers
| |
> CSM Installation Wizard:Disable Operator option for Powerflex and Unity 

- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template
- content/docs/deployment/csmoperator/_index.md
PowerScale: Add Max Volume limits support in Installation Wizard.
Update Driver version of csi-powerscale in csm-operator section
Run Sanity test
- Snapshot of file generated for helm install
- Snapshot of file generated for operator install
- Snapshot of environment variables for driver install
> PowerScale: Volume limits support in Installation Wizard

- content/docs/csidriver/upgradation/drivers/isilon.md
Powerscale upgrade document 
|https://github.com/dell/csm/issues/964|
> Powerscale Upgrade

- content/docs/deployment/csminstallationwizard/release/_index.md
- content/docs/deployment/csminstallationwizard/src/csm-versions/default-values.properties
- content/docs/deployment/csminstallationwizard/src/index.html
- content/docs/deployment/csminstallationwizard/src/static/js/generate-yaml.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/generate-yaml.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/tests/utility.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/static/js/utility.js
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.7.0-values.template
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
New keys added for CSI-PowerFlex driver for CSM 1.7 and CSM 1.8
> Installation Wizard: PowerFlex new keys added

- content/docs/csidriver/_index.md
- content/docs/csidriver/features/powerscale.md
- content/docs/csidriver/installation/helm/isilon.md
- content/docs/csidriver/release/powerscale.md
- content/docs/csidriver/upgradation/drivers/isilon.md
Updated CSI-PowerScale Release notes and documentation
> Updated CSI-PowerScale Release notes and documentation

- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template
- content/docs/snapshots/_index.md
- content/docs/snapshots/volume-group-snapshots/_index.md
Bumped csi-volumegroup-snapshotter version in [csm-1.8.0-values.template](https://github.com/dell/csm-docs/blob/release-1.8.0/content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.8.0-values.template)
> Bumped csi-volumegroup-snapshotter version

- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/modules/replication.md
- content/docs/deployment/csmoperator/troubleshooting/_index.md
Adding instructions for operator-initiated replication installations to create host aliases in deployed workloads. These additional host aliases will help resolve requests to API endpoints in remote clusters in environments where the DNS service is not configured to do so.
| https://github.com/dell/csm/issues/988 |
> Improve instructions for Replication installations that utilize CSM Operator

- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.8.0.template
Added volume-name-prefix in the CSM Installation Wizard for PowerStore
| KRV-18698 |
> Added volume-name-prefix in the Installation Wizard for PowerStore

- content/docs/csidriver/installation/helm/powermax.md
- content/docs/csidriver/installation/operator/powermax.md
- content/docs/deployment/csmoperator/drivers/powermax.md
- content/v1/csidriver/installation/helm/powermax.md
- content/v1/csidriver/installation/operator/powermax.md
- content/v2/csidriver/installation/helm/powermax.md
- content/v2/csidriver/installation/operator/powermax.md
- content/v3/csidriver/installation/helm/powermax.md
- content/v3/csidriver/installation/operator/powermax.md
The PowerPath and the multi-path software's should not be installed together, as Power-Path cannot co-exist with native multi-path software. Hence either of this should be installed.
Updating the documentation with this details.
|https://github.com/dell/csm/issues/1037|
> Power-Path and Multi-Path Software guidance for PowerMax

- content/docs/csidriver/_index.md
Documentation points to PowerScale 9.5.0.4, which is no longer available.  This PR updates the PowerScale supported versions by added 9.5.0.5 and 9.5.0.6.
> Update Supported PowerScale version

- content/docs/csidriver/_index.md
Change already went into main.  This is to put the change in the release-1.9.0 branch.  Documentation points to PowerScale 9.5.0.4, which is no longer available.  This PR updates the PowerScale supported versions by added 9.5.0.5 and 9.5.0.6.
> Updated supported versions of PowerScale

- content/docs/csidriver/_index.md
Updates to orchestrator and platform versions
| https://github.com/dell/csm/issues/1012  |
> Updates to orchestrator and platform versions

- content/docs/deployment/csminstallationwizard/src/static/js/tests/ui-functions.test.js
- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.7.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.8.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.9.0.template
Fixed volume-name-prefix in the CSM Installation Wizard for Powerscale
|https://github.com/dell/csm/issues/989 |
> Fixed volume-name-prefix in the Installation Wizard for Powerscale

- content/docs/csidriver/release/powerflex.md
Added fixed issue: PowerFlex Dockerfile is incorrectly labeling the version as 2.7.0 for the 2.8.0 version
| https://github.com/dell/csm/issues/1054 |
> PowerFlex: Added fixed issue for PowerFlex Dockerfile is incorrectly labeling the version as 2.7.0 for the 2.8.0 version

- config.toml
- content/docs/deployment/csminstallationwizard/src/index.html
- content/docs/deployment/csminstallationwizard/src/static/js/ui-functions.js
- content/docs/deployment/csminstallationwizard/src/static/js/utility.js
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
Previous version was displaying the entire form, now fixed in the javascript
Per request, add all `images` tags to the template
The tags on the left menu prevent to launch the `Interactive Tutorial`
- https://github.com/dell/csm/issues/1055
- https://github.com/dell/csm/issues/1012
> Fix interactive form, no tag menu, add images in template

- content/docs/csidriver/installation/operator/operator_migration.md
- Added references to the common migration steps page created  wherever there is a deprecation notice
- Updated v1 folder with the same changes as it contains the deprecation notice as well
Most of the original changes done as part of this PR are covered as part of PR https://github.com/dell/csm-docs/pull/887/files
Just keeping the diff after resolving conflicts. We can avoid merging this PR if the diff content need not go into the base branch
| https://github.com/dell/csm/issues/996|
> Feature 996 link migration steps op driver

- content/docs/csidriver/installation/test/certcsi.md
Clone the latest tag of cert-csi instead of main when building locally.
> [bug-1027]: Clone latest cert-csi tag

- content/docs/_index.md
- content/docs/authorization/_index.md
- content/docs/authorization/configuration/powerflex/_index.md
- content/docs/authorization/configuration/powermax/_index.md
- content/docs/authorization/configuration/powerscale/_index.md
- content/docs/csidriver/installation/offline/_index.md
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.9.0-values.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.9.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.9.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.9.0.template
- content/docs/deployment/csmoperator/_index.md
Update Authorization and Resiliency to v1.9.0.
Adds missing section for configuring CSI PowerMax with Authorization in the Operator.
> [feature-1012]: Update Authorization and Resiliency for CSM v1.9.0

- content/docs/csidriver/installation/test/certcsi.md
Lists cert-csi installation options more clear and provides examples of how to execute suites that require file arguments with the container image.
|https://github.com/dell/csm/issues/1027 |
> [bug-1027]: Make cert-csi installations more clear and provide examples for container image

- content/docs/csidriver/installation/operator/operator_migration.md
- content/docs/deployment/csmoperator/_index.md
Updated operator support matrix for unity 2.9 and updated operator sample file links to 2.9.
|https://github.com/dell/csm/issues/1012|
> Update operator support matrix for unity and operator sample files

- content/docs/csidriver/installation/test/certcsi.md
Adds notes stating that the Volume Expansion suite is expected to timeout for CSI PowerScale when SmartQuotas are disabled.
| https://github.com/dell/csm/issues/1046|
> [bug-1046]: Cert-CSI PowerScale Volume Expansion

- content/docs/csidriver/_index.md
The PowerMax NFS provider does not support a number of standard CSI call, reflecting it in the doc
| |
> Reflect true status of CSI compliance with NFS for PowerMax

- content/docs/deployment/csminstallationwizard/src/index.html
- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/release/_index.md
CSM Operator document changes for v1.4.1
|https://github.com/dell/csm/issues/1109 |
> CSM Operator document changes for CSM 1.9.1 patch release

- content/docs/authorization/cli.md
- content/docs/authorization/troubleshooting.md
Updating Authorization documentation for token refresh in case generated token didn't work.
| |
> Updating Authorization documentation

- config.toml
- content/docs/authorization/configuration/powerflex/_index.md
- content/docs/authorization/configuration/powermax/_index.md
- content/docs/authorization/configuration/powerscale/_index.md
- content/docs/authorization/release/_index.md
- content/docs/deployment/csminstallationwizard/_index.md
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.10.0-values.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-isilon-1.10.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.10.0 .template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powermax-1.8.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.10.0.template
- content/docs/deployment/csminstallationwizard/src/templates/operator/csm-powerstore-1.9.0.template
- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/csmoperator/modules/replication.md
- content/docs/deployment/csmoperator/modules/resiliency.md
- content/docs/deployment/helm/modules/replication/install-repctl.md
- content/docs/deployment/helm/modules/replication/install-script.md
- content/docs/deployment/offline/drivers/_index.md
- content/docs/observability/release/_index.md
- content/docs/observability/upgrade/_index.md
- content/docs/replication/upgrade.md
- content/docs/resiliency/release/_index.md
| https://github.com/dell/csm/issues/1091 |
> update latest versions for drivers and modules 

- content/docs/deployment/csmoperator/drivers/powerflex.md
- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/csmoperator/drivers/powerscale.md
- content/docs/deployment/csmoperator/drivers/powerstore.md
- content/docs/deployment/csmoperator/drivers/unity.md
Added sample file links for each driver in csm operator 
|(https://github.com/dell/csm/issues/1105)|
> added samples link for storage class for each driver in csm-operator

- content/docs/csidriver/_index.md
Reverting Kubernetes K3s as community supported only . 
|https://github.com/dell/csm/issues/1091 |
> Revert Kubernetes K3s support 

- content/docs/deployment/csmoperator/modules/authorization.md
- content/docs/deployment/csmoperator/modules/observability.md
- content/docs/deployment/helm/modules/authorization/_index.md
- content/docs/deployment/helm/modules/observability/deployment.md
Add missing step to enable Authorization sidecar for Observability via CSM Operator and fix broken links
|https://github.com/dell/csm/issues/1091 |
> CSM Operator documentation missing steps to enable Authorization sidecar for Observability

- content/docs/resiliency/uninstallation.md
Updated the resiliency uninstallation instructions to point directly to the uninstallation steps for helm deployments as well as operator deployments.
|https://github.com/dell/csm/issues/1091|
> Update resiliency uninstallation instructions

- content/docs/deployment/csmoperator/_index.md
- content/docs/observability/_index.md
Update csm-operator versions
| https://github.com/dell/csm/issues/1091 |
> CSM Operator docs update

- content/docs/deployment/csmoperator/_index.md
Removed "Perform Driver Installation" section from the Operator installation doc.  Reason is because it's misleading.  See linked GitHub issue for more details.
|https://github.com/dell/csm/issues/1186 |
> Cleanup operator doc

- content/docs/deployment/csmoperator/modules/authorization.md
Add notes about editing Operator sample files for non-authorization namespace.
| https://github.com/dell/csm/issues/1205|
> Add notes about non-default namespace for Authorization and Operator

- content/docs/csidriver/features/unity.md
Snapshot ingestion procedure for CSI Unity Driver.
|https://github.com/dell/csm/issues/1206|
> Snapshot ingestion procedure for CSI Unity Driver

- content/docs/deployment/helm/drivers/installation/powermax.md
- content/docs/deployment/helm/drivers/installation/powerstore.md
- content/docs/deployment/helm/drivers/upgrade/powermax.md
- content/docs/deployment/helm/drivers/upgrade/powerstore.md
- content/v1/csidriver/installation/helm/powermax.md
- content/v1/csidriver/installation/helm/powerstore.md
- content/v1/csidriver/upgradation/drivers/powermax.md
- content/v1/csidriver/upgradation/drivers/powerstore.md
- content/v2/csidriver/installation/helm/powermax.md
- content/v2/csidriver/installation/helm/powerstore.md
- content/v2/csidriver/upgradation/drivers/powermax.md
- content/v2/csidriver/upgradation/drivers/powerstore.md
Adding helm-charts-version flag for PowerMax and PowerStore
| https://github.com/dell/csm/issues/1218 |
> Adding helm-charts-version flag 

- content/docs/interactive-tutorials/_index.md
- content/docs/interactive-tutorials/csm-operator/_index.md
- content/docs/interactive-tutorials/csm-quickstart/_index.md
Adding the new Instruqt CSM Operator track
| |
> New CSM Operator interactive tutorial

- content/docs/deployment/csmoperator/_index.md
- content/docs/deployment/rpm/_index.md
Put the RPM install at the bottom of the left menu
| |
> Reorder deployment methods by priority

- content/docs/deployment/csmoperator/_index.md
- content/docs/prerequisites/_index.md
For the sake of clarity, moving the support matrix of CSM Operator in the prereqs section.
Add details explaining the differences between certified vs community edition
| |
> Move support matrix, clarify certified vs community

- content/docs/prerequisites/_index.md
Update VolumeGroupSnapshot support matrix
Align table so it easier to read in markdown
> Add VGS to the support matrix ; align tables

- content/docs/csidriver/features/powermax.md
- content/docs/csidriver/features/powerscale.md
- content/docs/csidriver/features/powerstore.md
- content/docs/csidriver/features/unity.md
- content/docs/csidriver/release/powerflex.md
- content/docs/csidriver/release/powermax.md
- content/docs/csidriver/release/powerscale.md
- content/docs/csidriver/release/powerstore.md
- content/docs/csidriver/release/unity.md
Update documentation around Single Pod Access Mode for PersistentVolumes- ReadWriteOncePod 
- Remove feature gate notes
- Remove alpha designation
- Update format of doc section for consistency
|[1287](https://github.com/dell/csm/issues/1287) |
> Update Single Pod Access Mode for PersistentVolumes- ReadWriteOncePod 

- .github/workflows/actions.yaml
- .github/workflows/broken-links.yaml
Added broken links check action
| https://github.com/dell/csm/issues/1289 |
> Added broken links check action

- content/docs/resiliency/_index.md
- content/v1/resiliency/_index.md
- content/v2/resiliency/_index.md
Updating the webpage for Resiliency (https://dell.github.io/csm-docs/docs/resiliency/) under the sub-topic "Not Yet Tested or Supported" to indicate that resiliency is not supported for the NFS protocol in PowerFlex.
|-----------------|
| dell/csm#1304 |
> Resiliency not supported for NFS in PowerFlex

- content/docs/deployment/csmoperator/modules/resiliency.md
- content/docs/deployment/helm/modules/installation/resiliency/_index.md
- content/docs/prerequisites/_index.md
- content/docs/resiliency/_index.md
Updated resiliency for Powermax in Helm and Operator
|https://github.com/dell/csm/issues/1082 |
> Update Resiliency Support for Powermax

- content/docs/deployment/csmoperator/modules/authorization.md
Add Vault documentation to Authorization deployment describing how to install a Vault server in a test environment and the configurations required.
Tested by executing each command to setup Vault, install Authorization with the generated client certificates, install Authorization, and create a storage resource.
| https://github.com/dell/csm/issues/1281|
> Add Vault documentation to Authorization deployment

- content/docs/authorization/Backup and Restore/rpm/_index.md
- content/docs/deployment/rpm/modules/installation/authorization/authorization.md
- content/v1/authorization/Backup and Restore/rpm/_index.md
- content/v1/authorization/deployment/rpm/_index.md
- content/v2/authorization/Backup and Restore/rpm/_index.md
- content/v2/authorization/deployment/rpm/_index.md
This PR updates the Authorization RPM deprecation message that's been in the documentation since CSM 1.8.  There is some inconsistent messaging in the Backup and Restore/Deployment sections that was fixed as part of this.  One of the messages was referencing CSM 2.0 which is an invalid version.
| |
> Updated the Authorization RPM deprecation message referencing an invalid version

- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template
- content/docs/deployment/csmoperator/drivers/unity.md
- content/docs/deployment/helm/drivers/installation/unity.md
csi-unity allowedNetworks param update
| https://github.com/dell/csm/issues/1335 |
> Bug 1335: csi-unity allowedNetworks param update

- content/docs/prerequisites/_index.md
Add note in prerequisites about "operations outside of the driver may not be supported or picked up by the driver"
| |
> Add note in prerequisites

- content/docs/csidriver/features/powerflex.md
Support Minimum 3GB Volume Size for NFS in CSI-PowerFlex
|https://github.com/dell/csm/issues/1366|
> Adding a note for NFS size

- content/docs/csidriver/troubleshooting/powerflex.md
- content/docs/deployment/csminstallationwizard/src/templates/helm/csm-1.11.0-values.template
- content/docs/deployment/helm/drivers/installation/powerflex.md
This PR update the SDC version in the documentation
|https://github.com/dell/csm/issues/1359 |
> Docs changes for SDC version Update

- content/docs/authorization/v1.x GA/configuration/powermax/_index.md
The CSI Powermax Reverse Proxy must be deployed as a sidecar for things to work with Authorization. This adds configuration steps for this.
|https://github.com/dell/csm/issues/1220 |
> [bug-1220]: Add configuration steps for Powermax with Authorization for reverseproxy

- content/docs/csidriver/_index.md
- content/v1/csidriver/_index.md
- content/v2/csidriver/_index.md
- content/v3/csidriver/_index.md
Update Access Mode for `volumeMode: Block` to RWO and RWX for Unity.
| https://github.com/dell/csm/issues/1363 |
> Update access mode for Unity

- content/docs/support/cert-csi/_index.md
- content/v1/csidriver/installation/test/certcsi.md
Ephemeral suite ephemeral-config.properties format fix
|https://github.com/dell/csm/issues/1381|
unity:
powerstore:
powerflex:
> Ephemeral suite ephemeral-config.properties format fix

- content/docs/support/cert-csi/_index.md
Updating the steps to download cert-csi and use it as a stand alone binary
|https://github.com/dell/csm/issues/1383|
> Updating the steps to download cert-csi

- content/docs/prerequisites/_index.md
- content/docs/resiliency/_index.md
- content/docs/support/cli/_index.md
Update versions and CLI samples
> Update versions and CLI samples

- hugo.toml
Fix for the link of feedback in modules and drivers, redirecting to relevant page.
| |
> Fix for the link of feedback

- content/docs/support/cli/_index.md
- Extend dellctl support to get the volume snapshots for PowerFlex.
- Make the dellctl command generic for the supported platforms while listing the Volumes and Snapshots. 
| |
> Documentation Update to get Volume Snapshots using dellctl

- content/docs/authorization/Migration guide from v1 to v2/_index.md
- content/docs/deployment/csmoperator/modules/authorization v2.0 Tech Preview.md
CSM for Authorization v2 is not backward compatible. This steps will guide existing CSM for Authorization v1 users how to migrate to v2.
| #https://github.com/dell/csm/issues/1281 |
> Add CSM for Authorization v1 to v2 migration guide

- content/docs/csidriver/_index.md
- content/v1/csidriver/_index.md
- content/v2/csidriver/_index.md
- content/v3/csidriver/_index.md
Update Powerflex Driver Capabilities in CSM docs that CSI Volume Cloning is not supported for nfs in Powerflex
| https://github.com/dell/csm/issues/1498|
> Powerflex capability matrix change

- content/docs/deployment/csmoperator/modules/resiliency.md
- content/docs/deployment/helm/modules/installation/resiliency/_index.md
- content/docs/resiliency/_index.md
Add a section in Resiliency that it should be disabled for storage array upgrades.
|https://github.com/dell/csm/issues/1435 |
> [feature-1435]: Disable Resiliency for Array Upgrades

- content/docs/csidriver/features/powerflex.md
- content/docs/deployment/csmoperator/drivers/powerflex.md
- content/docs/deployment/helm/drivers/installation/powerflex.md
Add information of the optional SDC feature for Powerflex.
| https://github.com/dell/csm/issues/663 |
> Add optional sdc documentation

- content/docs/deployment/helm/modules/installation/observability/_index.md
- Update version of Grafana supported by Observability.
- Add a note about deprecation messages with Angular plugins.
- Add a note about Grafana 11.x not yet being supported.
| https://github.com/dell/csm/issues/1435 |
> Update supported version of Grafana

- content/docs/_index.md
- content/docs/snapshots/volume-group-snapshots/_index.md
This PR adds notices to indicate that Volume Group Snapshotter will be deprecated in CSM 1.14 
|https://github.com/dell/csm/issues/1544|
> Add deprecation notice for Volume Group Snapshotter

- content/docs/deployment/helm/drivers/installation/isilon.md
- content/docs/deployment/helm/drivers/upgrade/isilon.md
A few isilon version updates were missed in the docs. This PR rectifies that.
| |
> Update missed versions for isilon

- content/docs/support/cert-csi/_index.md
Update cert-csi version
|https://github.com/dell/csm/issues/1435 |
> Update cert-csi version

- content/docs/support/cert-csi/_index.md
- content/v1/support/cert-csi/_index.md
- content/v2/support/cert-csi/_index.md
- content/v3/csidriver/installation/test/certcsi.md
This PR adds the missing `capacityTracking` test section in the certify config YAML example for CSI-PowerScale driver and adds a note for the requirement of volume binding mode to be set as `WaitForFirstConsumer`
| https://github.com/dell/csm/issues/1503 |
> CapacityTracking suite docs update

- content/docs/deployment/csmoperator/drivers/powermax.md
- content/v1/deployment/csmoperator/drivers/powermax.md
- content/v2/deployment/csmoperator/drivers/powermax.md
- content/v3/deployment/csmoperator/drivers/powermax.md
Removed the prerequisite of multiple secrets which is not necessary with the same cert and key for PowerMax driver in CSM-docs all versions.
|dell/csm#1557 |
> Remove the prerequisite of multiple secrets which is not necessary with the same cert and key

- .gitignore
- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/csmoperator/drivers/powerstore.md
- content/docs/deployment/helm/drivers/installation/powerflex.md
- content/docs/deployment/helm/drivers/installation/powermax.md
- content/docs/deployment/helm/drivers/installation/powerstore.md
- content/docs/deployment/helm/drivers/installation/unity.md
- content/docs/deployment/rpm/modules/installation/authorization-v1.x/authorization v1.x.md
Removed the references to CentOS in the installation instructions where RHEL is also mentioned. I left the sample YAMLs with the centos image as those can be cleaned up later and those are used more for demonstration purposes involving launching a pod.
|https://github.com/dell/csm/issues/1467|
> Clean up iSCSI requirements and remove CentOS references in instructions

- content/docs/deployment/csmoperator/_index.md
Remove reference to APEX Navigator for Kubernetes in the CSM Operator documentation.
| https://github.com/dell/csm/issues/1572 |
> Remove reference to APEX Navigator for Kubernetes

- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/helm/drivers/installation/powermax.md
The sample configmap for the csi-powermax reverseproxy had ambiguous secret names -- that is being fixed [here](https://github.com/dell/csi-powermax/pull/366), and this PR makes an accompanying doc change.
| https://github.com/dell/csm/issues/1568 |
> Update CSI-PowerMax ReverseProxy Configmap Sample

- content/docs/support/cert-csi/qualified.md
Community Qualification Update for CSIv2.12.0
Support confirmation for CSIv2.12.0 on MKE 3.6.13, OKE 4.14.31 for PowerScale and PowerFlex.
|https://github.com/dell/csm/issues/1622|
|https://github.com/dell/csm/issues/1623|
|https://github.com/dell/csm/issues/1624|
|https://github.com/dell/csm/issues/1625|
> Community Qualification Update - CSIv2.12.0

- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/csmoperator/drivers/powerstore.md
- content/docs/deployment/helm/drivers/installation/powermax.md
- content/docs/deployment/helm/drivers/installation/powerstore.md
Per user feedback we added notes for resolving duplicated host NQNs for OCP nodes. The addition of a machine config to the OCP cluster will generate a unique host NQN for each node.
|https://github.com/dell/csm/issues/1643 |
Tested config on an OCP cluster and validated that the configuration was applied to each node and unique NQNs were generated. Noteworthy that the NQNs remained the same (but still unique) after node reboot.
> Add note covering non unique host NQNs on OCP.

- content/docs/deployment/csmoperator/drivers/powermax.md
- content/v1/deployment/csmoperator/drivers/powermax.md
Document update for Powermax Metro 
|https://github.com/dell/csm/issues/1559|
> Document update for Powermax Metro 

- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/helm/drivers/installation/powermax.md
- content/v1/deployment/csmoperator/drivers/powermax.md
- content/v1/deployment/helm/drivers/installation/powermax.md
Powermax doc update on reverse proxy cert
| https://github.com/dell/csm/issues/1698 |
> Powermax doc update on reverse proxy cert

- content/docs/csidriver/features/powerstore.md
- content/v1/csidriver/features/powerstore.md
- content/v2/csidriver/features/powerstore.md
- content/v3/csidriver/features/powerstore.md
Clarified the protocol to be 'scsi' for block-based protocol and 'nfs' for file-based protocol.
| https://github.com/dell/csm/issues/1729 |
> Clarified protocol use in PowerStore

- Makefile
This PR adds Makefile targets to run GitHub Actions checks locally:
`actions` Target :
Runs all pull request checks with enhanced logging.
`action-help` Target :
Displays instructions for running specific workflows with act.
Usage:
Run all PR checks: `make actions`
Get workflow instructions: `make action-help`
Enhances local testing and debugging of GitHub Actions.
| https://github.com/dell/csm/issues/1490|
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration
> Csm-docs/Add Makefile Targets for Local PR Checks

- content/docs/csidriver/features/powermax.md
- content/docs/deployment/csmoperator/drivers/powermax.md
- content/docs/deployment/helm/drivers/installation/powermax.md
- layouts/shortcodes/message.html
Updating install documentation to guide users through the process of installing csi-powermax using the reverse proxy secret with CSM Operator.
| https://github.com/dell/csm/issues/1614 |
> Add PowerMax Mount Credentials for installation with Operator

- content/docs/getting-started/installation/installationwizard/src/templates/helm/csm-1.12.0-values.template
- content/docs/getting-started/installation/installationwizard/src/templates/helm/csm-1.13.0-values.template
Fix the powermax-array-config not generated/configured correctly when using the Installation Wizard. Moving the 3 fields(transport protocol, managed arrays and port groups under global section
| (https://github.com/dell/csm/issues/1786) |
> Fix the powermax-array-config not generated/configured correctly when using the Installation Wizard

- content/v1/csidriver/release/powermax.md
Adding a release note for PowerMax installation issue using Helm charts where a ConfigMap is incorrectly created with multiple `X_CSI_POWERMAX_ENDPOINT` entries. This issue occurs only on CSM 1.13 release. Since this part has been removed in 1.14, there are no code changes needed. Workaround steps have been added.
| https://github.com/dell/csm/issues/1760 |
> Add release note for PowerMax multiple X_CSI_POWERMAX_ENDPOINT entry issue

- content/docs/concepts/csidriver/features/powerstore.md
- content/docs/getting-started/installation/kubernetes/powerstore/prerequisite/_index.md
- content/docs/getting-started/installation/openshift/powerstore/prerequisite/_index.md
- content/v1/csidriver/features/powerstore.md
- content/v1/deployment/csmoperator/drivers/powerflex.md
- content/v1/deployment/helm/drivers/installation/powerflex.md
Add shared NFS (host based NFS) capability. It provides an outline of the feature with a sample storage class. Also added a line in prerequisites for helm and operator installation of CSI powerstore driver. 
|https://github.com/dell/csm/issues/1742 |
> Add host based NFS capability

- content/docs/support/contributionguidelines/_index.md
Removed the git submodule update --recursive --init step from the "Previewing your changes" subsection under the Contributing Guidelines, as it is no longer required. Verified that the site builds and runs correctly without it.
|https://github.com/dell/csm/issues/1707|
> Update hugo Deployment Steps

- .github/workflows/release-notes.yaml
Update the `GITHUB_TOKEN` to correct PAT.
| https://github.com/dell/csm/issues/1707 |
> Fix: Use Proper PAT for Release Notes Generation

- content/docs/getting-started/installation/kubernetes/powermax/csmoperator/_index.md
- content/docs/getting-started/installation/openshift/powermax/csmoperator/_index.md
Revert the Powermax Metro note from v1.14 doc
Issue is addressed in https://github.com/dell/csi-powermax/pull/417 and https://github.com/dell/csm-docs/pull/1429
|https://github.com/dell/csm/issues/1711|
> Revert the Powermax Metro note

- content/docs/concepts/csidriver/troubleshooting/powerflex.md
- content/docs/release/_index.md
Added a workaround to the troubleshooting table for minimal PowerFlex installations that fail due to a nil reference in the Operator.
|https://github.com/dell/csm/issues/1895|
> Powerflex Minimal Manifest Documentation Update

- content/docs/concepts/replication/high-availability/powerstore-metro.md
This PR replaces the incorrect metro architecture diagram that was previously showing PowerMax with the correct diagram for PowerStore. 
| dell/csm#1898|
Screenshot:
> Update image of PowerStore Metro Architecture

- content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-isilon-1.14.0.template
- content/docs/getting-started/installation/installationwizard/src/templates/operator/csm-isilon-1.15.0.template
- content/docs/getting-started/installation/openshift/powerscale/csmoperator/_index.md
For the PowerScale CreateSnapshot call, the required isiPath is now retrieved from the source volume's export path like it is done in the replication code. So, there will be no need to get PV's 'Path' value or remove any prefix. Hence, reverting the changes made in previous PR https://github.com/dell/csm-docs/pull/1521 for 1.15 template.
Related PRs:
https://github.com/dell/csi-powerscale/pull/406
https://github.com/dell/csm-operator/pull/1012
https://github.com/dell/helm-charts/pull/753
| https://github.com/dell/csm/issues/1920 |
> Removing csi-vol prefix variable for csi-powerscale template as it is no longer needed

- content/docs/getting-started/installation/openshift/powermax/prerequisite/_index.md
Fixed a broken link in PowerMax reverse-proxy information.
This PR is for live doc.
main/1.15 branch does not have this issue in docs and v1 versions.
| https://github.com/dell/csm/issues/1923 |
> Fix broken link

- .github/workflows/csi-sidecars-update.yaml
- content/docs/getting-started/installation/offline/helm.md
- content/docs/getting-started/installation/offline/operator.md
- content/docs/tooling/cli/_index.md
- layouts/shortcodes/version-docs.html
**Depends On:** https://github.com/dell/common-github-actions/pull/168
Adds the GitHub action to manually trigger and periodically update the CSI sidecars throughout the installation and CSM docs through the use of shortcodes.
The shortcodes syntax for the CSI sidecars to be more descriptive and better aligned to the naming convention of the tags. This change has been tested and ensured that the substitution still works as expected.
An example of the GitHub action running can be found: https://github.com/falfaroc/csm-docs/pull/10.
| |
> Add CSI Sidecars Update Action

- content/docs/getting-started/installation/openshift/powermax/prerequisite/_index.md
Fix wrong reference to FC in the iSCSI section of the PowerMax docs.
|https://github.com/dell/csm/issues/1933 |
> Remove FC reference in iSCSI prerequisite in PowerMax.

- content/docs/getting-started/installation/operator/modules/observability.md
- content/docs/getting-started/installation/operator/openshift_modules/observability.md
PR to remove karavi namespace dependency  from documentation. 
Linked PR: https://github.com/dell/csm-operator/pull/1027
| https://github.com/dell/csm/issues/1896|
> Removed karavi namespace dependency from csm-operator for observability

- .github/workflows/csi-sidecars-update.yaml
Fix the formatting of the csi sidecar update action. This was causing it to not run periodically.
| |
> Fix indentation of cron jon for sidecar action

- content/docs/getting-started/installation/openshift/powerscale/csmoperator/_index.md
- content/v1/getting-started/installation/openshift/powerscale/csmoperator/_index.md
To rename secret for powerscale as isilon-creds in documentation for ocp environment. It should be isilon-creds instead of isilon-config.
|https://github.com/dell/csm/issues/1955 |
> Renaming powerscale secret name from isilon-config to isilon-creds

- content/docs/getting-started/installation/helm/modules/authorizationv2-0.md
- content/docs/getting-started/installation/operator/modules/authorizationv2-0.md
- Use tabs for Authorization storage credential options to indicate that only one method should be used.
- Move SecretProviderClass or Secret options to its own installation step.
| https://github.com/dell/csm/issues/1972|
> [bug-1972]: Use tabs for Authorization storage credential options

- content/docs/concepts/csidriver/troubleshooting/powerstore.md
This reverts commit 920f2a0cf6d8d48b8892b95e45c38b823c306af7.
The potential issue that this warning message addressed has been resolved at the driver level. 
| https://github.com/dell/csm/issues/2012 |
> Revert "Warning Message - Too Long Contexts  (#1652)"

- content/v1/supportmatrix/component-version.md
Updated the compatibility matrix with the image versions for CSM 1.1.5. Same changes as [PR 1673](https://github.com/dell/csm-docs/pull/1673).
| E960 |
> Add sha256 sums for images in 1.15 release.

- content/docs/concepts/authorization/v2.x/configuration/powerflex/_index.md
- content/docs/concepts/authorization/v2.x/configuration/powermax/_index.md
- content/docs/concepts/authorization/v2.x/configuration/powerscale/_index.md
- content/docs/concepts/authorization/v2.x/configuration/powerstore/_index.md
- content/docs/getting-started/upgrade/helm/module/authorization.md
- content/docs/getting-started/upgrade/operator/authorization_upgrade.md
Doc changes for removing the dependency on the karavi-authorization-config secret for deploying Auth v2 with PowerStore, PowerFlex, PowerScale, and PowerMax. 
New deployments only require the driver secret, simplifying the configuration process. Existing deployments using the karavi-authorization-config secret will continue to function as expected, ensuring seamless upgrades.
| https://github.com/dell/csm/issues/1583 |
> Simplify Auth v2 deployment by removing karavi-authorization-config Secret requirement
